### ISSUE TITLE
Should not output error messages to browser as HTML

### ISSUE THREAD

**Issue by adamthehutt** [apereo/phpCAS#129]
When a CAS_AuthenticationException is thrown, error messages are outputted directly to the browser, which is not user-friendly and also a security concern. Even more importantly, none of the relevant debugging data is available to the application's normal exception handler. 

This should be refactored so that the exception is thrown as normal and the application can be responsible for handling it and outputting any error message to the browser.

**Comment by bkdotcom** [comment]
ditto... 
temporary workaround via output buffering

**Comment by jfritschi** [comment]
The security part of this issue was fixed in #152. Refactoring the whole error message stack is a topic for a later point in time.

**Comment by jfritschi** [comment]
Has been addressed in PR #393
