### ISSUE TITLE
Move to Apereo?

### ISSUE THREAD

**Issue by mmoayyed** [apereo/phpCAS#194]
Given that Jasig no longer exists, this repo probably should be moved to Apereo. 

I can assist with the move, if you'd like to proceed.

**Comment by jfritschi** [comment]
Sure, sounds like a plan.
Is that a real move or copy and delete?

**Comment by mmoayyed** [comment]
Real move. All history, settings, forks and such is preserved though.

**Comment by jfritschi** [comment]
Sounds great. How do we proceed from here?

**Comment by mmoayyed** [comment]
Sure. Tough if u have those already they should transfer over and continue without issues. 

I'll work on the move shortly. Stay tuned.

**Comment by ChristianMurphy** [comment]
@mmoayyed Any update on this?

**Comment by mmoayyed** [comment]
@jfritschi 

The repository is now moved. You along with @adamfranco should also have admin access to the repo. You should be receiving an invitation from Github shortly, asking you to join the Apereo organization on Github. Once you do, you will auto-enter the PHPCAS developers team here and will be set to continue. LMK if you run into any weirdness please.
