### ISSUE TITLE
Success authentication but invalid redirect or...

### ISSUE THREAD

**Issue by meysamjavadi** [apereo/phpCAS#225]
I integrated my ZendFramework 1 project with [this](https://github.com/Jasig/phpCAS/blob/master/docs/examples/example_simple.php) example.

```
	require_once 'Cas/config.php' ;
	require_once 'Cas/CAS.php' ;
	phpCAS::setDebug("/var/www/html/tums/library/Cas/ooo.log");
	phpCAS::setVerbose(true);
	phpCAS::client(CAS_VERSION_2_0, $cas_host, $cas_port, $cas_context);
	phpCAS::setNoCasServerValidation();
	$auth = phpCAS::checkAuthentication();
	if($auth)
		echo "Salam!";
	else
	{
		phpCAS::forceAuthentication();
		echo "bbbbbbbbbbbbbbbbbbbbbbb";
	}

```
When User is not logged in phpCAS redirect to CAS login page properly but when User logged in  `phpCAS::checkAuthentication()` redirects project with multiple times and after two times phpCAS returned `not recognized` message. What should i do?

**Comment by jfritschi** [comment]
Please try one of our default examples.

https://github.com/Jasig/phpCAS/blob/master/docs/examples/example_gateway.php

This should work. If not, please have have look at the debug log and share if problems cannot be resolved.

**Comment by meysamjavadi** [comment]
Thank you for your response. It's not. This is my log content:
```
EDAD .START (2017-05-09 23:20:23) phpCAS-1.3.4 ****************** [CAS.php:469]
EDAD .=> phpCAS::client('2.0', '192.168.70.216', 8443, '/cas') [LoginController.php:62]
EDAD .|    => CAS_Client::__construct('2.0', false, '192.168.70.216', 8443, '/cas', true) [CAS.php:361]
EDAD .|    |    Ticket 'ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org' found [Client.php:989]
EDAD .|    <= ''
EDAD .<= ''
EDAD .=> phpCAS::setNoCasServerValidation() [LoginController.php:64]
EDAD .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
EDAD .<= ''
EDAD .=> phpCAS::forceAuthentication() [LoginController.php:68]
EDAD .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
EDAD .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
EDAD .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
EDAD .|    |    |    |    no user found [Client.php:1604]
EDAD .|    |    |    <= false
EDAD .|    |    |    CAS 2.0 ticket `ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org' is present [Client.php:1416]
EDAD .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1419]
EDAD .|    |    |    |     [Client.php:3127]
EDAD .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3134]
EDAD .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
EDAD .|    |    |    |    |    |    Final URI: https://192.168.70.20/login/ [Client.php:3497]
EDAD .|    |    |    |    |    <= 'https://192.168.70.20/login/'
EDAD .|    |    |    |    <= 'https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F'
EDAD .|    |    |    |    => CAS_Client::_readURL('https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F&ticket=ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org', NULL, NULL, NULL) [Client.php:3149]
EDAD .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
EDAD .|    |    |    |    |    |    Response Body: 
EDAD .|    |    |    |    |    |    
EDAD .|    |    |    |    |    |    
EDAD .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
EDAD .|    |    |    |    |    |        <cas:authenticationFailure code='INVALID_TICKET'>
EDAD .|    |    |    |    |    |                Ticket &#039;ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org&#039; not recognized
EDAD .|    |    |    |    |    |        </cas:authenticationFailure>
EDAD .|    |    |    |    |    |    </cas:serviceResponse>
EDAD .|    |    |    |    |    |    
EDAD .|    |    |    |    |    |     [CurlRequest.php:84]
EDAD .|    |    |    |    |    <= true
EDAD .|    |    |    |    <= true
EDAD .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F&ticket=ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org', false, false, '<cas:serviceResponse xmlns:cas=\'http://www.yale.edu/tp/cas\'>    <cas:authenticationFailure code=\'INVALID_TICKET\'>            Ticket &#039;ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org&#039; not recognized    </cas:authenticationFailure></cas:serviceResponse>', 'INVALID_TICKET', 'Ticket \'ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org\' not recognized') [Client.php:3240]
EDAD .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
EDAD .|    |    |    |    |    <= 'https://192.168.70.20/login/'
EDAD .|    |    |    |    |    CAS URL: https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F&ticket=ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org [AuthenticationException.php:79]
EDAD .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
EDAD .|    |    |    |    |    Reason: [INVALID_TICKET] CAS error: Ticket 'ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org' not recognized [AuthenticationException.php:96]
EDAD .|    |    |    |    |    CAS response: 
EDAD .|    |    |    |    |    
EDAD .|    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
EDAD .|    |    |    |    |        <cas:authenticationFailure code='INVALID_TICKET'>
EDAD .|    |    |    |    |                Ticket &#039;ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org&#039; not recognized
EDAD .|    |    |    |    |        </cas:authenticationFailure>
EDAD .|    |    |    |    |    </cas:serviceResponse>
EDAD .|    |    |    |    |     [AuthenticationException.php:101]
EDAD .|    |    |    |    |    exit()
EDAD .|    |    |    |    |    -
EDAD .|    |    |    |    -
EDAD .|    |    |    -
EDAD .|    |    -
EDAD .|    -

```

**Comment by meysamjavadi** [comment]
Thank you for your response. It's not. This is my log content:
EDAD .START (2017-05-09 23:20:23) phpCAS-1.3.4 ****************** [CAS.php:469]
EDAD .=> phpCAS::client('2.0', '192.168.70.216', 8443, '/cas') [LoginController.php:62]
EDAD .|    => CAS_Client::__construct('2.0', false, '192.168.70.216', 8443, '/cas', true) [CAS.php:361]
EDAD .|    |    Ticket 'ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org' found [Client.php:989]
EDAD .|    <= ''
EDAD .<= ''
EDAD .=> phpCAS::setNoCasServerValidation() [LoginController.php:64]
EDAD .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
EDAD .<= ''
EDAD .=> phpCAS::forceAuthentication() [LoginController.php:68]
EDAD .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
EDAD .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
EDAD .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
EDAD .|    |    |    |    no user found [Client.php:1604]
EDAD .|    |    |    <= false
EDAD .|    |    |    CAS 2.0 ticket `ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org' is present [Client.php:1416]
EDAD .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1419]
EDAD .|    |    |    |     [Client.php:3127]
EDAD .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3134]
EDAD .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
EDAD .|    |    |    |    |    |    Final URI: https://192.168.70.20/login/ [Client.php:3497]
EDAD .|    |    |    |    |    <= 'https://192.168.70.20/login/'
EDAD .|    |    |    |    <= 'https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F'
EDAD .|    |    |    |    => CAS_Client::_readURL('https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F&ticket=ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org', NULL, NULL, NULL) [Client.php:3149]
EDAD .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
EDAD .|    |    |    |    |    |    Response Body: 
EDAD .|    |    |    |    |    |    
EDAD .|    |    |    |    |    |    
EDAD .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
EDAD .|    |    |    |    |    |        <cas:authenticationFailure code='INVALID_TICKET'>
EDAD .|    |    |    |    |    |                Ticket &#039;ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org&#039; not recognized
EDAD .|    |    |    |    |    |        </cas:authenticationFailure>
EDAD .|    |    |    |    |    |    </cas:serviceResponse>
EDAD .|    |    |    |    |    |    
EDAD .|    |    |    |    |    |     [CurlRequest.php:84]
EDAD .|    |    |    |    |    <= true
EDAD .|    |    |    |    <= true
EDAD .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F&ticket=ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org', false, false, '<cas:serviceResponse xmlns:cas=\'http://www.yale.edu/tp/cas\'>    <cas:authenticationFailure code=\'INVALID_TICKET\'>            Ticket &#039;ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org&#039; not recognized    </cas:authenticationFailure></cas:serviceResponse>', 'INVALID_TICKET', 'Ticket \'ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org\' not recognized') [Client.php:3240]
EDAD .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
EDAD .|    |    |    |    |    <= 'https://192.168.70.20/login/'
EDAD .|    |    |    |    |    CAS URL: https://192.168.70.216:8443/cas/serviceValidate?service=https%3A%2F%2F192.168.70.20%2Flogin%2F&ticket=ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org [AuthenticationException.php:79]
EDAD .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
EDAD .|    |    |    |    |    Reason: [INVALID_TICKET] CAS error: Ticket 'ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org' not recognized [AuthenticationException.php:96]
EDAD .|    |    |    |    |    CAS response: 
EDAD .|    |    |    |    |    
EDAD .|    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
EDAD .|    |    |    |    |        <cas:authenticationFailure code='INVALID_TICKET'>
EDAD .|    |    |    |    |                Ticket &#039;ST-15-PduvUy7qemLM2c4pOllm-cas01.example.org&#039; not recognized
EDAD .|    |    |    |    |        </cas:authenticationFailure>
EDAD .|    |    |    |    |    </cas:serviceResponse>
EDAD .|    |    |    |    |     [AuthenticationException.php:101]
EDAD .|    |    |    |    |    exit()
EDAD .|    |    |    |    |    -
EDAD .|    |    |    |    -
EDAD .|    |    |    -
EDAD .|    |    -
EDAD .|    -

**Comment by meysamjavadi** [comment]
I used this simple code:
```

		require_once 'Cas/config.php' ;
		require_once 'Cas/CAS.php' ;
		phpCAS::setDebug("/var/www/html/tums/library/Cas/ooo.log");
		phpCAS::setVerbose(true);

		phpCAS::client(CAS_VERSION_2_0, $cas_host, $cas_port, $cas_context);
		
		phpCAS::setNoCasServerValidation();

		//phpCAS::setCasServerCACert('/var/www/t/ca.crt');

		phpCAS::forceAuthentication();
			
		$auth = phpCAS::checkAuthentication();
		//var_dump($auth);
		if($auth)
			echo "Salam!";
		else
		{
			//phpCAS::forceAuthentication();
			echo "bbbbbbbbbbbbbbbbbbbbbbb";
		}
```

**Comment by meysamjavadi** [comment]
I think phpCAS felt into a redirect loop.

**Comment by meysamjavadi** [comment]
I debugged my code.It originated from Zend Framework. The example you mentioned works fine but when migrated that code to my Zend Framework controller it felt to infinite loop.

**Comment by jfritschi** [comment]
This might be due to the cookie changes by phpCAS. You should disable the phpcas session management. The only downside ist that you will have no single sign out capabilities:

https://developer.jasig.org/cas-clients/php/1.3.4/docs/api/group__publicInit.html#ga15e9a325862a20edfbd9e862b49738a5

**Comment by jfritschi** [comment]
Closing, no further updates for almost a year.
