### ISSUE TITLE
readme.md with no install doc!

### ISSUE THREAD

**Issue by pokapow** [apereo/phpCAS#242]
You didn't provied installation and configuration documentation in you readme.md, so can we find this doc elsewhere ?
I found also this project which seems to be close to yours: https://github.com/leo108/php_cas_server (with complete readme.md...)

Is there a link between this two projects ? Same kind library use do same kind of install and configuration ?

**Comment by phy25** [comment]
Install doc: https://wiki.jasig.org/display/CASC/phpCAS+installation+guide

If you look further, that project is a server, and this project is an official client.

**Comment by pokapow** [comment]
Thank you for your reactivity! I didn't see it was a client side here ... Sorry and thank you for the doc.
Now I have to install the server side first ^^

**Comment by phy25** [comment]
OK if you think this is no longer an issue, please close this.
