### ISSUE TITLE
phpCAS and redirection

### ISSUE THREAD

**Issue by MartinFous** [apereo/phpCAS#245]
Help mi please, how set redirect back to my website, where the user was before login.

If is the user on site xxx.php and click on hyperlink "login" and set your name and password for CAS server and login, I need your redirect back on xxx.php. Now I have set redirect on one website, but it is not ideal.

**Comment by adamfranco** [comment]
Martin, your application will need to handle this state and redirect -- this is beyond the scope of phpCAS and the CAS server.

For example, an application might always show a "user" page after logging in. Alternatively, an application might look for a "destination" parameter in a URL and redirect to that URL after logging in. Still another application might not have any redirects, but initiate the phpCAS login-flow directly on protected pages and then stay on that page once an authenticated session is established.

If you need to redirect, that code should come after the call to `phpCAS::forceAuthentication();`

**Comment by jfritschi** [comment]
No further updates after month
