### ISSUE TITLE
Add support for longer tickets

### ISSUE THREAD

**Issue by johnthomasmorton** [apereo/phpCAS#248]
The CAS server we are using (Shibboleth 3.3) allows for the encoding of new information in the ticket. This extra information removes the need for a shared/distributed caching layer normally needed to support the CAS protocol's serviceValidate operation when you have multiple load balanced CAS servers. This feature is great, and we have seen it working with the Apereo Java CAS client. Thanks to @serac for the great potential of this feature.

The only downside of this feature is that it makes the ticket longer.

phpCAS works great with shorter tickets such as (42 characters, this was generated prior to enabling the feature described above):
"ST-1508970944633-d0imWIM4l7uuwPPHDYXXUkffZ"

phpCAS returns a 500 instead of a 302 when it is passed longer tickets such as (351 characters, this was generated after enabling the feature described above):
"ST-AAhzZWNyZXQyMtCVw87kLFMV5zBvTqR6H9WI0crqq7s10JaDrxBVPQLjLN_xWDCdFRBpKaq2NbIiem8KGY90PupiZW5Hg037KtOxf3bVyBEpp8rzUX28Um4WkcAMgdKUWtJZWuYBSnYuEeGRBZDISGv7RilAMOd26EgJKL18gHSmvyh0g9WC4m6XJ8UsObu0MLqBRJg6RlFs_rfO2lJboM03KMXyZtK7hoV_Nr9-KwhS84oAaKA6rvvvA-oOZghFg25E7qTPLC1BQU08Cs93pHN9JTB9ZViEOTFHkMyWmnFuXzsfM2cUGc8cGZITzEqxhkMutkYUWr1KcqvXmL42lZ_2EzdI"

I'd love to point out where in the codebase this could be addressed, but I am not a PHP developer.

Is this something that could be addressed?

phpCAS 1.3.5
php  7.0.21

Sincerely,
John Morton

**Comment by phy25** [comment]
See http://php.net/manual/en/session.configuration.php#ini.session.sid-length: `Session ID length can be between 22 to 256`.

Somewhat related (but their issue is that ticket ID is shorter than 22) at #224.

**Comment by johnthomasmorton** [comment]
Also definitely related to #244. The code for ticket length and/or format would also need to be touched in #240.

How interested are you in addressing? These longer tickets open up the great possibility of easier maintenance and reduced complexity on. The server side with regards to caching.
