### ISSUE TITLE
CAS error: E_ILLEGAL_STATE

### ISSUE THREAD

**Issue by dmaniad** [apereo/phpCAS#249]
Hello everyone,
I am trying to get phpCAS client working with a cas server (configured shibboleth v3 to work as cas server).
I installed and configured phpCAS client and tried to check-in using example_html.php. However, after filling in credentials, I get:

Authentication failure: Ticket not validated
Reason: [INTERNAL_ERROR] CAS error: E_ILLEGAL_STATE

Is it probably an error in the phpCAS client or in the cas server?
Is this a response from the cas server?
What should I check in the cas server side? Which log?
Lastly, what is E_ILLEGAL_STATE?

The log in /tmp/phpCAS.log is:

```
=> CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 
'https://XXXXXX/idp/profile/cas/serviceValidate?service=http%3A%2F%2FYYYYYYYY%2Fhtml%2FCAS-1.3.5%2Fdocs%2Fexamples%2Fexample_html.php&ticket=ST-1509374777848-PsC2i6LlXmgr5QCCWWZ2AKUdo', false, false, 
'<?xml version="1.0" encoding="UTF-8"?><cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">  <cas:authenticationFailure code="INTERNAL_ERROR">    E_ILLEGAL_STATE  </cas:authenticationFailure></cas:serviceResponse>', 'INTERNAL_ERROR', 'E_ILLEGAL_STATE') [Client.php:3241]
=> CAS_Client::getURL() [AuthenticationException.php:77]
<= 'http://YYYYYYYY/html/CAS-1.3.5/docs/examples/example_html.php'
CAS URL: https://XXXXXX/idp/profile/cas/serviceValidate?service=http%3A%2F%2FYYYYYYYY%2Fhtml%2FCAS-1.3.5%2Fdocs%2Fexamples%2Fexample_html.php&ticket=ST-1509374777848-PsC2i6LlXmgr5QCCWWZ2AKUdo [AuthenticationException.php:80]
Authentication failure: Ticket not validated [AuthenticationException.php:81]
Reason: [INTERNAL_ERROR] CAS error: E_ILLEGAL_STATE [AuthenticationException.php:97]
CAS response: <?xml version="1.0" encoding="UTF-8"?>
<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
  <cas:authenticationFailure code="INTERNAL_ERROR">
	E_ILLEGAL_STATE
  </cas:authenticationFailure>
</cas:serviceResponse>
 [AuthenticationException.php:102]
exit()
```

**Comment by jfritschi** [comment]
The error is embedded in the xml cas server answer. Please check the logs of the cas server. Check the logs of you application server e.g. Tomcat and the logs of the cas server itself.

For server support this is not the right location. I will close this issue.
