### ISSUE TITLE
Invalid Session ID Error 

### ISSUE THREAD

**Issue by jcarn** [apereo/phpCAS#250]
When phpCAS::client is called, I immediately get an Invalid Session ID error. Error log of one login attempt below.

https://pastebin.com/ZYdN9tYm

**Comment by phy25** [comment]
```php
is_string( $id ) && preg_match( '/^[a-zA-Z0-9_-]{32,}$/', $id )
```

https://github.com/wikimedia/mediawiki/blob/d18fa74c4dbc9d2597a36d04a3344cf1bb5a371c/includes/session/SessionManager.php#L371

Could you please post one of the "invalid" sesison ID or check whether the session ID meet the requirements? Actually in most cases the session ID is the ticket. You may workaround this by initializing client with ``phpCAS::client('', '', '', '', FALSE)`` if you don't need the session logout feature.

**Comment by jcarn** [comment]
Looks like the id generator function was making id's that didn't match the regex length there. Thanks for pointing me in that direction!
