### ISSUE TITLE
function __autoload() is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by XuZhixuan** [apereo/phpCAS#254]
When using php7.2 , the function __autoload() while cause error. Especially in the case of using the framework ThinkPHP.
The using of __autoload() in source/CAS/autoload.php Line 90

```
elseif (!function_exists('__autoload')) {
    /**
     * Autoload a class
     *
     * @param string $class Class name
     *
     * @return bool
     */
    function __autoload($class)
    {
        return CAS_autoload($class);
    }
}
```
may should be deleted.

**Comment by eseyden** [comment]
Why did you close this issue? Is there a working release?
