### ISSUE TITLE
Update tests to support PHPUnit 7

### ISSUE THREAD

**Issue by adamfranco** [apereo/phpCAS#256]
As noted at https://phpunit.de/ , PHPUnit 5.7 was the last version to support PHP 5.x.

Testing on PHP 7.1 with PHPUnit 7.0.2 indicates that new versions of PHPUnit will require our tests to be refactored to use new (namespaced) class names and method signatures.

As PHP 5.6 will [reach end-of-life on December 31, 2018](http://php.net/supported-versions.php), it likely makes sense to update tests as part of a new version of phpCAS that drops PHP 5.6 support.

**Comment by phy25** [comment]
During my work in #320 I found that the first non backward-compatible PHPUnit should be 8.0.

We still have a long list of 5.x tests in Travis CI. Not sure when to drop support of them.

**Comment by jfritschi** [comment]
I have just dropped php 5.x from our build scripts and test are currently running on phpunit 7.5.x
