### ISSUE TITLE
Authentication failed with CAS

### ISSUE THREAD

**Issue by miquelsabate** [apereo/phpCAS#259]
I have installed a CAS server with a public domain and it works correctly. I implemented PHPCas in the same server and it works correctly too, and I was able to authenticate me on it.

Now I want to use my other public domain with different services with CAS authentication but, after login in CAS, when I redirect to these services, PHPCas tell me "Authentication failed, you were not authenticated"

I have been searching for a long time and I couldn't find any solution. What I need is to keep the CAS session between two servers.

The configuration of PHPCas authentication is:

```php
phpCAS::client(CAS_VERSION_2_0,'example.com', 8443,'/cas', TRUE);
```
The url is this: http://client.com/portal.php?ticket=ST-..... so the ticket is granted, why is failiing the authentication?

The procedure is the following one:
```php
include_once("../CAS.php"); 
//initialize phpCAS (CAS Version, CAS Server, Port, Base URI, Should phpCAS start a PHP Session?)
phpCAS::client(CAS_VERSION_2_0,'example.com', 8443,'/cas', TRUE); 
 
//For development. Prints out additional warnings. 
phpCAS::setDebug(); 
phpCAS::setVerbose(true);
 
//no SSL validation for the CAS server 
phpCAS::setNoCasServerValidation(); 
 
//force CAS authentication. 
phpCAS::forceAuthentication();
```

What can I do? 
setVerbose only tells me the PHPcas version and what CAS server is used. I don't have any logfile in /tmp (I don't know why)

Thanks!

**Comment by adamfranco** [comment]
Please have have look at the debug log (configured with `phpCAS::setDebug('/path/to/file');` and share if problems cannot be resolved.

**Comment by miquelsabate** [comment]
Hi @adamfranco thanks for your answer. I have this in my code: `phpCAS::setDebug('./log.txt');` but when I enter into webpage by a device through the public domain, no file is created :(

The problem is that when I receive the authentication failed, the URL have a ticket number. CAS server and webpage are different server, but I think that it shouldn't be a problem

**Comment by adamfranco** [comment]
Here is your error:
` could not open URL 'https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-43-bcpN1lrL0uxok07f9Xf4-cas' to validate (CURL error #7: Failed to connect to XX.com port 8443: Connection refused) `

Given that phpCAS in your application is trying to connect to your CAS server on `8443` (a non-standard port) it is likely that firewall rules are blocking access to the CAS server from your application server. Try accessing that URL from the command line on your application server with `curl` to see if you can even connect. Example:

`curl -i https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-43-bcpN1lrL0uxok07f9Xf4-cas`

If the connection is working, this should return you XML with an error message if the ticket is expired. If you aren't getting any XML then you probably have issues with networking or firewall.

**Comment by miquelsabate** [comment]
Hi @adamfranco thanks for your answer. I have been investigating with code and firewall and I tried to access through internal network, and it doesn't work. I got an URL like https://XX.com:8443/newlogin/v1/portal.php?service=ST-46....

I did a curl -i as you said with this URL and I obtained this problem: `curl (60): ssl certificate problem: self signed certificate`

Via intern network I obtained it, what is the problem? I did all the steps, probably I need a real CA and not self signed? Thanks!

**Comment by adamfranco** [comment]
When using curl ([manual](https://curl.haxx.se/docs/manpage.html)) you can specify the certificate authority to use with the `--cacert` option (similar to what `phpCAS::setCasServerCACert()`) or disable certificate validation with the `-k` option (similar to what `phpCAS::setNoCasServerValidation()` does).

**Comment by miquelsabate** [comment]
Hi @adamfranco , a month later I'm not able to solve this issue... I have some questions in order to get a solution (if it's possible).

My system works like this:
![captura](https://user-images.githubusercontent.com/22028946/38867052-26ab07f8-4243-11e8-82db-acb330c05764.PNG)

 A is the web server and B is the CAS server. I access to A.com/portal.php and I'm redirected to B:8443/cas. I login into CAS server and, after searching my user in LDAP server (located in B) I'm redirected to A.com/portal.php another time with a ticket as a parameter. In that point, the screen shows phpCAS authentication failed error, like I said in the comments above.

I have thinking and investigating about it and my question is, if I'm able to be redirected from A to B and from B to A, can we discard the firewall or not? I disabled all rules from B and it doesn't work.

The firewall of A is more complex but I have a rule TCP/UDP and destination is *.

I tried curl as you said (with -k option) and I didn't get any response. You said that it can be firewall but, as I said, can we discard it if I can be redirected from A to B and from B to A?

Service ticket is granted but I can't be logged in phpCAS::forceauthentication method, it shows the error.

I'm waitint for your answer. I hope you can help me. Thanks for all!

**Comment by jfritschi** [comment]
You are missing a crucial point:
When you are redirected with the ticket as a parameter to your application the phpcas client tries to validate the ticket with the server. (called "validates ticket" in your picture)

This is a direct connection between your cas client (your webserver A) and the CAS server (B). This is done with curl and as @adamfranco has told you can be replicated with the curl commandline client.

You are currently getting a curl error #7 which can be looked up on https://curl.haxx.se/libcurl/c/libcurl-errors.html  It's basically a network connection error.  

This means it definitely an network error you have sort out on your end:
- Can your CAS server be pinged by IP, DNS (done from the webserver!)
- Can you manually reach the port via a commandline CURL command (done from the webserver!). Detail see above in Adams posts

I suspect you did the curl tests from your own PC and not the webserver itself....

**Comment by miquelsabate** [comment]
Hi @jfritschi , obviously I did it with webserver, not with my own PC :)
In fact, yesterday I did it another time and I got this results:

- In webserver I pinged the IP B and I got response. Later I used nmap in order to check if the port 8443 was opened and yes, it was. B:8443 gave me response (port 8443/tcp open)
![image](https://user-images.githubusercontent.com/22028946/39037566-264a2b1e-4481-11e8-9f5f-4be9e7043128.png)

- After that I followed the @adamfranco's post. I got the URL with webserver (going to CAS, login there and trying to access to portal.php). I used these URL to try curl (curl -i -k URL). I got this response:
![image](https://user-images.githubusercontent.com/22028946/39037488-f523c810-4480-11e8-9f9c-adcec42a7a27.png)

What can be the error? Thanks for your answers!

**Comment by miquelsabate** [comment]
Hi @jfritschi , both servers are not running on the same hostname. The webserver is running on an IP, and the CAS server is running on another IP. They are different servers and machines, and they are connected with a local network.

The webserver executes phpCAS on default port of apache and CAS server executes CAS service via Tomcat server on port 8443.

I don't understand what you mean about curl debug and phpCAS::setExtraCurlOption() (this last one I don't know what parameters I have to put)

Anyway. I have done another test trying to connect to portal.php (the web that executes phpCAS) with my own PC (independent from webserver and CAS server) and I have got this log:

> 718B .START (2018-04-23 13:03:16) phpCAS-1.3.5+ ****************** [CAS.php:468]
> 718B .=> phpCAS::client('2.0', 'IP_CASserver', 8443, '/cas') [portal.php:10]
> 718B .|    => CAS_Client::__construct('2.0', false, 'IP_CASserver', 8443, '/cas', true) [CAS.php:360]
> 718B .|    |    Starting a new session fvhprn3s3k27ip1m4211ff5f67 [Client.php:932]
> 718B .|    |    Session is not authenticated [Client.php:938]
> 718B .|    <= ''
> 718B .<= ''
> 718B .=> phpCAS::setNoCasServerValidation() [portal.php:13]
> 718B .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1644]
> 718B .<= ''
> 718B .=> phpCAS::forceAuthentication() [portal.php:16]
> 718B .|    => CAS_Client::forceAuthentication() [CAS.php:1098]
> 718B .|    |    => CAS_Client::isAuthenticated() [Client.php:1280]
> 718B .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1393]
> 718B .|    |    |    |    no user found [Client.php:1635]
> 718B .|    |    |    <= false
> 718B .|    |    |    no ticket found [Client.php:1494]
> 718B .|    |    <= false
> 718B .|    |    => CAS_Client::redirectToCas(false) [Client.php:1289]
> 718B .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1656]
> 718B .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
> 718B .|    |    |    |    |    Final URI: https://www.IP_webserver/portal.php [Client.php:3549]
> 718B .|    |    |    |    <= 'https://www.IP_webserver/portal.php'
> 718B .|    |    |    <= 'https://IP_CASserver:8443/cas/login?service=https%3A%2F%2Fwww.IP_webserver%2Fportal.php'
> 718B .|    |    |    Redirect to : https://IP_CASserver:8443/cas/login?service=https%3A%2F%2Fwww.IP_webserver%2Fportal.php [Client.php:1663]
> 718B .|    |    |    exit()
> 718B .|    |    |    -
> 718B .|    |    -
> 718B .|    -
> AC1E .START (2018-04-23 13:03:29) phpCAS-1.3.5+ ****************** [CAS.php:468]
> AC1E .=> phpCAS::client('2.0', 'IP_CASserver', 8443, '/cas') [portal.php:10]
> AC1E .|    => CAS_Client::__construct('2.0', false, 'IP_CASserver', 8443, '/cas', true) [CAS.php:360]
> AC1E .|    |    Starting a new session fvhprn3s3k27ip1m4211ff5f67 [Client.php:932]
> AC1E .|    |    Session is not authenticated [Client.php:938]
> AC1E .|    |    Ticket 'ST-14-hXvca1dq0b5BBiFWCzR9-cas' found [Client.php:1020]
> AC1E .|    <= ''
> AC1E .<= ''
> AC1E .=> phpCAS::setNoCasServerValidation() [portal.php:13]
> AC1E .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1644]
> AC1E .<= ''
> AC1E .=> phpCAS::forceAuthentication() [portal.php:16]
> AC1E .|    => CAS_Client::forceAuthentication() [CAS.php:1098]
> AC1E .|    |    => CAS_Client::isAuthenticated() [Client.php:1280]
> AC1E .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1393]
> AC1E .|    |    |    |    no user found [Client.php:1635]
> AC1E .|    |    |    <= false
> AC1E .|    |    |    CAS 2.0 ticket `ST-14-hXvca1dq0b5BBiFWCzR9-cas' is present [Client.php:1447]
> AC1E .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1450]
> AC1E .|    |    |    |     [Client.php:3170]
> AC1E .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3177]
> AC1E .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
> AC1E .|    |    |    |    |    |    Final URI: https://www.IP_webserver/portal.php [Client.php:3549]
> AC1E .|    |    |    |    |    <= 'https://www.IP_webserver/portal.php'
> AC1E .|    |    |    |    <= 'https://IP_CASserver:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.IP_webserver%2Fportal.php'
> AC1E .|    |    |    |    => CAS_Client::_readURL('https://IP_CASserver:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.IP_webserver%2Fportal.php&ticket=ST-14-hXvca1dq0b5BBiFWCzR9-cas', NULL, NULL, NULL) [Client.php:3192]
> AC1E .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
> AC1E .|    |    |    |    |    |    Response Body: 
> AC1E .|    |    |    |    |    |    

The steps are the same (portal.php redirects me to CAS login, I login succesfully and I'm redirected to portal.php with a ticket as a parameter but in portal.php I get authentication failed), but the error is different, probably now you can help me. Thanks for all!

**Comment by jfritschi** [comment]
Yes, now you get an response from the CAS server:
```
AC1E .| | | | | | Response Body:
AC1E .| | | | | | ���
AC1E .| | | | | |
AC1E .| | | | | | [CurlRequest.php:84]
```
Something is however broken with the response. The XML contents is garbled. The question marks we can see here may indicate some kind of language/character issues between CAS server/client. (or it may be github?)
You may also want to consult your CAS server logs and check what happens during this validation (you may need to enable debug flags for the CAS server). Any troubles you now have are most likely on the CAS server side.

You can ignore the curl debug comment. The connection seems to be working now.

**Comment by miquelsabate** [comment]
Hi @jfritschi , response body has symbols and github converts them into question marks. These symbols are  (see image below). In fact, all of the question marks of the log I put are this symbol.
![image](https://user-images.githubusercontent.com/22028946/39233346-63ed4576-4870-11e8-83b5-cf57fd0bd526.png)

Here you have the log of Tomcat server for the same login:

> 2018-04-25 09:49:28,450 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 0 services.>
> 2018-04-25 09:51:28,447 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
> Hibernate: select registered0_.id as id0_, registered0_.allowedToProxy as allowedT2_0_, registered0_.anonymousAccess as anonymou3_0_, registered0_.description as descript4_0_, registered0_.enabled as enabled0_, registered0_.evaluation_order as evaluation6_0_, registered0_.ignoreAttributes as ignoreAt7_0_, registered0_.name as name0_, registered0_.serviceId as serviceId0_, registered0_.ssoEnabled as ssoEnabled0_, registered0_.theme as theme0_ from RegisteredServiceImpl registered0_
> 2018-04-25 09:51:28,455 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 0 services.>
> 2018-04-25 09:53:28,447 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
> Hibernate: select registered0_.id as id0_, registered0_.allowedToProxy as allowedT2_0_, registered0_.anonymousAccess as anonymou3_0_, registered0_.description as descript4_0_, registered0_.enabled as enabled0_, registered0_.evaluation_order as evaluation6_0_, registered0_.ignoreAttributes as ignoreAt7_0_, registered0_.name as name0_, registered0_.serviceId as serviceId0_, registered0_.ssoEnabled as ssoEnabled0_, registered0_.theme as theme0_ from RegisteredServiceImpl registered0_
> 2018-04-25 09:53:28,450 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 0 services.>
> 2018-04-25 09:55:28,447 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
> Hibernate: select registered0_.id as id0_, registered0_.allowedToProxy as allowedT2_0_, registered0_.anonymousAccess as anonymou3_0_, registered0_.description as descript4_0_, registered0_.enabled as enabled0_, registered0_.evaluation_order as evaluation6_0_, registered0_.ignoreAttributes as ignoreAt7_0_, registered0_.name as name0_, registered0_.serviceId as serviceId0_, registered0_.ssoEnabled as ssoEnabled0_, registered0_.theme as theme0_ from RegisteredServiceImpl registered0_
> 2018-04-25 09:55:28,452 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 0 services.>
> 2018-04-25 09:57:28,448 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>
> Hibernate: select registered0_.id as id0_, registered0_.allowedToProxy as allowedT2_0_, registered0_.anonymousAccess as anonymou3_0_, registered0_.description as descript4_0_, registered0_.enabled as enabled0_, registered0_.evaluation_order as evaluation6_0_, registered0_.ignoreAttributes as ignoreAt7_0_, registered0_.name as name0_, registered0_.serviceId as serviceId0_, registered0_.ssoEnabled as ssoEnabled0_, registered0_.theme as theme0_ from RegisteredServiceImpl registered0_
> 2018-04-25 09:57:28,451 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Loaded 0 services.>
> 2018-04-25 09:58:07,246 INFO [org.jasig.cas.authentication.AuthenticationManagerImpl] - <AuthenticationHandler: org.jasig.cas.adaptors.ldap.BindLdapAuthenticationHandler successfully authenticated the user which provided the following credentials: [username: XXXXXXXXX]>
> 2018-04-25 09:58:07,328 INFO [org.jasig.cas.CentralAuthenticationServiceImpl] - <Granted service ticket [ST-17-BIrbvAgOdEGRALFNHtJd-cas] for service [https://www.IP_webserver/portal.php] for user [XXXXXXXXX]>

It seems that CAS works correctly and it grants tickets in a good way... What can be the error? As you said, response body is weird (CAS response and some parameters too). Can the error be this part of XML? What could be happening?

Thanks!

**Comment by jfritschi** [comment]
You CAS log does not seem to be about the right call. The ST granting is normally the step where the ST is transmitted via URL back to the phpcas client.
You should for something with "validate" in the logs. (No sure what it's called)

With regard to the strange CAS server answer. I could be character/language related but that's just a wild guess. This issue is however outside of phpCAS ans therefor we cannot really help much from our end...

**Comment by miquelsabate** [comment]
Hi @adamfranco and @jfritschi , I'm me another time xD

I have a small issue due to the same as before. Now it works perfect in local network, but if I try to connect from external network I'm able to connect to cas, login to it and be redirected to the portal.php, but phpCAS fails in authentication.

**FYI:**

I'm trying to connect with an external PC connected, for example, in a mobile phone network (just for example, it's an external network). As you know, webserver and CAS server are different servers, but they are working in local network, so it shouldn't be the problem.

Log error:

> => CAS_Client::_readURL('https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-37-HPiecE9oDwVpNbndeAte-cas', NULL, NULL, NULL) [Client.php:3191]
> B1AA .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
> B1AA .|    |    |    |    |    |    **curl_exec() failed [CurlRequest.php:77]**
> B1AA .|    |    |    |    |    <= false
> B1AA .|    |    |    |    <= false
> B1AA .|    |    |    |    could not open URL 'https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-37-HPiecE9oDwVpNbndeAte-cas' to validate **(CURL error #7: Failed to connect to XX.com port 8443: Connection refused) [Client.php:3194]**
> B1AA .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-37-HPiecE9oDwVpNbndeAte-cas', true) [Client.php:3198]
> B1AA .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:77]
> B1AA .|    |    |    |    |    <= 'https://www.XX.com/newlogin/v1/portal.php'
> B1AA .|    |    |    |    |    CAS URL: https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-37-HPiecE9oDwVpNbndeAte-cas [AuthenticationException.php:80]
> B1AA .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:81]
> B1AA .|    |    |    |    |    Reason: no response from the CAS server [AuthenticationException.php:83]
> B1AA .|    |    |    |    |    exit()

With the same PC connected to the same network  I tried this:

`curl -i -k https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-37-HPiecE9oDwVpNbndeAte-cas` and I get the same screen than post above:
https://user-images.githubusercontent.com/22028946/39037488-f523c810-4480-11e8-9f9c-adcec42a7a27.png

Furthermore, I have scanned the port 8443 from the PC to domain (https://XX.com):

`nmap -p8443 https://XX.com` => 8443/tcp open https-alt

So... curl returns info (with error 500), port is opened to external networks but in log I get connection refused. What can I try to solve it?

I repeat, in local network it works, now I need to open to public networks.

Thanks for all!

**Comment by miquelsabate** [comment]
I want to update with some information.

If I enter the URL of validateService with service and ticket (https://xx.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-37-HPiecE9oDwVpNbndeAte-cas) on browser I get the username correctly, so I don't know why in the transaction of phpCAS is not working.

Waiting for your answers, thanks!

**Comment by jfritschi** [comment]
Sorry, but you will have to figure this out yourself. We cannot debug network, routing or dns issues remotely.

Just one observation: An error 500 is an internal server error. So there must be some issue with the server. Check the server logs.

**Comment by miquelsabate** [comment]
Thanks @jfritschi , I understand you. I will try to get a solution. If I get it, I will post here for future related issues.

I close the thread, thanks for your help!

**Comment by miquelsabate** [comment]
For future issues of that type I have found the problem!

I was connecting to CAS server with an URL that later, from CAS, it was not identified. What I did was adding a new line in Client.php, in function _readURL which replaces the URL depending on the "environment".

I add this: $url = str_replace("https://www.XXXX:8442", "https://YYYYY.com:8442", $url);

And it works! Thanks for your help!

**Comment by dixitDrc** [comment]
@adamfranco 
you suggested in previous comment as per below
---------------------------
curl -i https://XX.com:8443/cas/serviceValidate?service=https%3A%2F%2Fwww.XX.com%2Fnewlogin%2Fv1%2Fportal.php&ticket=ST-43-bcpN1lrL0uxok07f9Xf4-cas

If the connection is working, this should return you XML with an error message if the ticket is expired. If you aren't getting any XML then you probably have issues with networking or firewall.
----------------------------

So i do the same and get the XML with an error message as per below. can you guide me what's wrong with this issue.

<?xml version='1.0' encoding='UTF-8'?>
<cas:serviceResponse xmlns:cas="http://www.xxx.xxx/xx/cas"><cas:authenticationFailure code="INVALID_REQUEST">No ticket string provided</cas:authenticationFailure></cas:serviceResponse>
