### ISSUE TITLE
Attributes refresh

### ISSUE THREAD

**Issue by marekmueller** [apereo/phpCAS#260]
Hello,

is there possibility to refresh attributes? I need to watch if something has changed on CAS server (user roles).

**Comment by adamfranco** [comment]
The [CAS protocol](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol.html) will [return attributes](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#255-attributes-cas-30) as part of the authentication response, but doesn't have a mechanism for fetching / re-fetching the attributes outside of an authentication response. The only way I can think to accomplish this via the CAS protocol would be to force a user to re-authenticate periodically and refresh the attributes at that time.

Another option (totally unrelated to phpCAS) is to use some other out-of-band mechanism to lookup user attributes independent of the CAS server and the authentication sequence. I've built [this kind of service](https://github.com/middlebury/CAS_Directory/) in the past to look-up attributes directly from our ActiveDirectory, but this has the downside of adding yet another dependency to the system architecture and can be pretty environment-specific.

**Comment by marekmueller** [comment]
@adamfranco thank You for response, it's all i need to know.
