### ISSUE TITLE
use http instead https, the client.php has some trouble

### ISSUE THREAD

**Issue by Yyyyyoly** [apereo/phpCAS#261]
```
 private function _getServerBaseURL()
    {
        // the URL is build only when needed
        if ( empty($this->_server['base_url']) ) {
            **$this->_server['base_url'] = 'http://' . $this->_getServerHostname();**
            if ($this->_getServerPort()!=443) {
                $this->_server['base_url'] .= ':'
                .$this->_getServerPort();
            }
            $this->_server['base_url'] .= $this->_getServerURI();
        }
        return $this->_server['base_url'];
    }

we can see that if "base_url" is empty,  there doesn't handle the difference between 'https' and 'http'.
I wonder if the main branch can update the code like below:
```
    private function _getServerBaseURL()
    {
        // the URL is build only when needed
        if ( empty($this->_server['base_url']) ) {
            **$uri_type = ($this->_isHttps()) ? 'https://' : 'http://';
            $this->_server['base_url'] = $uri_type . $this->_getServerHostname();**
            if ($this->_getServerPort()!=443) {
                $this->_server['base_url'] .= ':'
                .$this->_getServerPort();
            }
            $this->_server['base_url'] .= $this->_getServerURI();
        }
        return $this->_server['base_url'];
    }

**Comment by jfritschi** [comment]
Running you CAS server over http is a recipe for disaster... This is why we do not support it with the automatic generation. 

You are welcome to override all the default generated URLs with the set* functions...

Also the flag you are using is depending on the phpcas client application http status and not the CAS server.
