### ISSUE TITLE
Session variable is lost after redirection

### ISSUE THREAD

**Issue by mvcmaker** [apereo/phpCAS#267]
Hi,
I've the next code in the index.php in the example phpcas library:
```
// force CAS authentication
phpCAS::forceAuthentication();

if (isset($_REQUEST['logout'])) {
    phpCAS::logout();
}

$attr=phpCAS::getAttributes();

$_SESSION['phpCAS'] = $attr;
//print_r($_SESSION);
//die();
header("Location: " . PUBLIC_URL . "user/login");
```

The problem is that, when I'm redirected to my site user/login endpoing (is a laravel site), the $_SESSION variable is not set. Why the $_SESSION variable is lost aften redirection even if the PUBLIC_URL is in the same directory as the phpCas library? Is this a bug? How can I access to the phpCAS returned user data after my redirection?

**Comment by adamfranco** [comment]
Hi @mvcmaker , either your application, its framework, or phpCAS needs to start the session-handling with `session_start()` and optionally set a session id parameter that is used for session cookies.

The [final argument of `phpCAS::client()`](https://github.com/apereo/phpCAS/blob/master/source/CAS.php#L323-L340) tells phpCAS to manage the session and set the session id itself. Set this to `false` if your application is already starting/managing the session.

**Comment by mvcmaker** [comment]
Yes, I know that, my own laravel method contains this:
```
public function login() {
		$ret = array();
		try {
			// CHECK for php cas authenticated user
			if($this->rest_method == 'GET') {
				// Try to check phpCas authenticated data
				require_once BASE_PATH . "lib/phpCAS/funcions.php";
				require_once BASE_PATH . "lib/phpCAS/config.php";
				require_once BASE_PATH . "lib/phpCAS/{$phpcas_path}/CAS.php";
				$session = parent::getSession();
				//print_r($_SESSION);
				print_r($session);
				phpCAS::client(CAS_VERSION_3_0, $cas_host, $cas_port, $cas_context);
				phpCAS::setNoCasServerValidation();


				var_dump(phpCAS::getAttributes());
				return false;
			}
```
Where the metdho ```getSession()``` contains the ```session_start()``` you mention. The print_r call always prints null.

**Comment by mvcmaker** [comment]
Solved, the problem is that phpCAS generates another sessionId that differs from the app sessionId is generated, so I need to reuse the sessionId that generates phpCAS to get the data returned from a successfull login.
