### ISSUE TITLE
Show custom error messages on CAS Authentication failure 

### ISSUE THREAD

**Issue by fgf2001** [apereo/phpCAS#268]
Hi, I need to know if it is possible, take the original authentication error message and show the correct message.
I explain myself better: I want to know if it can be detected when the email is not written correctly and to make the error: "Wrong email".
When the password is incorrect: show incorrect password,
I mean to show the correct message that the service returns when a login error occurs.
What I have achieved so far, is to take in menssages.properties

authenticationFailure.AccountNotFoundException = Invalid credentials.
authenticationFailure.FailedLoginException = Invalid credentials.

but I need to be more specific with the causes, for which the error occurred.

I'm waiting

Grateful in advance ...

Fernando

**Comment by adamfranco** [comment]
Hi Fernando it appears you have found the wrong issue queue. This is an issue queue for the phpCAS application-side library, not the CAS server. These exceptions and messages are part of the CAS server. When invalid credentials are entered the user stays on the CAS server and does not get redirected back to the application (and phpCAS). 

The CAS server application doesn't have an issue queue itself. Questions should be sent to the cas-user mailing list: https://groups.google.com/a/apereo.org/forum/#!forum/cas-user
