### ISSUE TITLE
Cas authentication failed with no generated session id files

### ISSUE THREAD

**Issue by mvcmaker** [apereo/phpCAS#274]
Hi, I get the next error log lines after a successfull validation on CAS server (notice that the url has been altered due privacy). On the frontpage, it appears the attached image:

![captura de pantalla 2018-09-04 13 17 19](https://user-images.githubusercontent.com/4662121/45028572-de15c200-b045-11e8-94c1-f6ea1f67686c.png)

> EA1D .START (2018-09-04 13:22:18) phpCAS-1.3.4 ****************** [CAS.php:469]
> EA1D .=> phpCAS::client('3.0', 'remotecasserver.com', 443, '', false) [index.php:45]
> EA1D .|    => CAS_Client::__construct('3.0', false, 'remotecasserver.com', 443, '', false) [CAS.php:360]
> EA1D .|    <= ''
> EA1D .<= ''
> EA1D .=> phpCAS::setNoCasServerValidation() [index.php:57]
> EA1D .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
> EA1D .<= ''
> EA1D .=> phpCAS::forceAuthentication() [index.php:79]
> EA1D .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
> EA1D .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
> EA1D .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
> EA1D .|    |    |    |    no user found [Client.php:1604]
> EA1D .|    |    |    <= false
> EA1D .|    |    |    no ticket found [Client.php:1463]
> EA1D .|    |    <= false
> EA1D .|    |    => CAS_Client::redirectToCas(false) [Client.php:1258]
> EA1D .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1625]
> EA1D .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
> EA1D .|    |    |    |    |    Final URI: http://localclient.com/sborrow/lib/phpCAS/ [Client.php:3497]
> EA1D .|    |    |    |    <= 'http://localclient.com/sborrow/lib/phpCAS/'
> EA1D .|    |    |    <= 'https://remotecasserver.com/login?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F'
> EA1D .|    |    |    Redirect to : https://remotecasserver.com/login?service=http%3A%2F%2Fremoteclient.com%2Fsborrow%2Flib%2FphpCAS%2F [Client.php:1632]
> EA1D .|    |    |    exit()
> EA1D .|    |    |    -
> EA1D .|    |    -
> EA1D .|    -
> 930F .START (2018-09-04 13:22:26) phpCAS-1.3.4 ****************** [CAS.php:469]
> 930F .=> phpCAS::client('3.0', 'remotecasserver.com', 443, '', false) [index.php:45]
> 930F .|    => CAS_Client::__construct('3.0', false, 'remotecasserver.com', 443, '', false) [CAS.php:360]
> 930F .|    |    Ticket 'ST-2264-vYtggH0gZfxdnWRV0bLi-remotecasserver.com,' found [Client.php:989]
> 930F .|    <= ''
> 930F .<= ''
> 930F .=> phpCAS::setNoCasServerValidation() [index.php:57]
> 930F .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
> 930F .<= ''
> 930F .=> phpCAS::forceAuthentication() [index.php:79]
> 930F .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
> 930F .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
> 930F .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
> 930F .|    |    |    |    no user found [Client.php:1604]
> 930F .|    |    |    <= false
> 930F .|    |    |    CAS 3.0 ticket `ST-2264-vYtggH0gZfxdnWRV0bLi-reemotecasserver.com' is present [Client.php:1415]
> 930F .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1418]
> 930F .|    |    |    |     [Client.php:3127]
> 930F .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3134]
> 930F .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
> 930F .|    |    |    |    |    |    Final URI: http://localclient.com/sborrow/lib/phpCAS/ [Client.php:3497]
> 930F .|    |    |    |    |    <= 'http://localclient.com/sborrow/lib/phpCAS/'
> 930F .|    |    |    |    <= 'https://remotecasserver.com/p3/serviceValidate?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F'
> 930F .|    |    |    |    => CAS_Client::_readURL('https://remotecasserver.com/p3/serviceValidate?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F&ticket=ST-2264-vYtggH0gZfxdnWRV0bLi-remotecasserver.com', NULL, NULL, NULL) [Client.php:3149]
> 930F .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
> 930F .|    |    |    |    |    |    curl_exec() failed [CurlRequest.php:77]
> 930F .|    |    |    |    |    <= false
> 930F .|    |    |    |    <= false
> 930F .|    |    |    |    could not open URL 'https://remotecasserver.com/p3/serviceValidate?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F&ticket=ST-2264-vYtggH0gZfxdnWRV0bLi-remotecasserverver.com' to validate (CURL error #6: Could not resolve host: remotecasserver.com) [Client.php:3151]
> 930F .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://remotecaserver.com/p3/serviceValidate?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F&ticket=ST-2264-vYtggH0gZfxdnWRV0bLi-remotecasserver.com', true) [Client.php:3155]
> 930F .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
> 930F .|    |    |    |    |    <= 'http://localclient.com/sborrow/lib/phpCAS/'
> 930F .|    |    |    |    |    CAS URL: https://remotecasserver.com/p3/serviceValidate?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F&ticket=ST-2264-vYtggH0gZfxdnWRV0bLi-remotecasserver.com [AuthenticationException.php:79]
> 930F .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
> 930F .|    |    |    |    |    Reason: no response from the CAS server [AuthenticationException.php:82]
> 930F .|    |    |    |    |    exit()
> 930F .|    |    |    |    |    -
> 930F .|    |    |    |    -
> 930F .|    |    |    -
> 930F .|    |    -
> 930F .|    -

**Comment by jfritschi** [comment]
You have a DNS resolution error or something similar.

could not open URL 'https://remotecasserver.com/p3/serviceValidate?service=http%3A%2F%2Flocalclient.com%2Fsborrow%2Flib%2FphpCAS%2F&ticket=ST-2264-vYtggH0gZfxdnWRV0bLi-remotecasserverver.com' to validate (CURL error #6: Could not resolve host: remotecasserver.com) 

You can look up the CURL error here:
https://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by mvcmaker** [comment]
[Solved]Sorry, I forget to tell you that reading accuratelly the log lines, I've found just this error that is the fail of our server, for one reason, this server can't access to the cas authentication server (by IP cans, but no by it's dns name).
