### ISSUE TITLE
My CAS Stop at forceauthentication

### ISSUE THREAD

**Issue by mhanifahns** [apereo/phpCAS#276]
iam trying to use phpcas lib for codeigniter https://github.com/eliasdorneles/code-ig...as-library

but when iam trying to testing it on controller it stuck on success login view and its doesnt redirect back to my apps.
here is the log and the code

code:
<pre>
$this->load->library('cas');
  $this->cas->force_auth();
  $user = $this->cas->user();
  print_r($this->cas);

  print_r($user);
</pre>
log:
C0C1 .START phpCAS-1.1.3 ****************** [CAS.php:470]
C0C1 .=> phpCAS::client('2.0', 'sso.xxxx.com', 443, '/casadfs') [Cas.php:55]
C0C1 .| => CASClient::CASClient('2.0', false, 'sso.xxxx.com', 443, '/casadfs', true) [CAS.php:373]
C0C1 .| | Starting a new session [client.php:600]
C0C1 .| <= ''
C0C1 .<= ''
C0C1 .=> phpCAS:ConfusedetNoCasServerValidation() [Cas.php:59]
C0C1 .<= ''
C0C1 .=> phpCAS::forceAuthentication() [Cas.php:74]
C0C1 .| => CASClient::forceAuthentication() [CAS.php:893]
C0C1 .| | => CASClient::isAuthenticated() [client.php:869]
C0C1 .| | | => CASClient::wasPreviouslyAuthenticated() [client.php:975]
C0C1 .| | | | no user found [client.php:1111]
C0C1 .| | | <= false
C0C1 .| | | no ticket found [client.php:1028]
C0C1 .| | <= false
C0C1 .| | => CASClient::redirectToCas(false) [client.php:878]
C0C1 .| | | => CASClient::getServerLoginURL(false, false) [client.php:1128]
C0C1 .| | | | => CASClient::getURL() [client.php:361]
C0C1 .| | | | | Final URI: http://localhost/sbis/trunk/src/app/login/testSSO2 [client.php:2686]
C0C1 .| | | | <= 'http://localhost/sbis/trunk/src/app/login/testSSO2'
C0C1 .| | | <= 'https://sso.xxxx.com/casadfs/login?service=http%3A%2F%2Flocalhost%2Fsbis%2Ftrunk%2Fsrc%2Fapp%2Flogin%2FtestSSO2'
C0C1 .| | | Redirect to : https://sso.xxxx.com/casadfs/login?service=http%3A%2F%2Flocalhost%2Fsbis%2Ftrunk%2Fsrc%2Fapp%2Flogin%2FtestSSO2
C0C1 .| | | exit()
C0C1 .| | | -
C0C1 .| | -
C0C1 .| -

iam stuck at this log the CAS didnt print my $user = $this->cas->user();

**Comment by jfritschi** [comment]
Please try some of our examples and report any errors. We have little change to remotely debug any custom code on top of our library....

It looks like your user is redirected to the cas server but never "returns" with any ticket....

**Comment by mhanifahns** [comment]
i have tried using your example https://github.com/apereo/phpCAS/tree/master/docs/examples
the result is same iam stuck at success notification
<pre>
Log In Successful
You have successfully logged into the Central Authentication Service.

For security reasons, please Log Out and Exit your web browser when you are done accessing services that require authentication!
</pre>
it doesnt redirect back to my example web but when i check the cookies i got two cookies SESSION and CASTGC. CASTGC is the ticket right? 

other apps working fine with this CAS Server but i cant get the CAS setup/mod if there was any mod because there's no documentation on other apps CAS client.

**Comment by mhanifahns** [comment]
the server CAS changing the host thats why its become an error
