### ISSUE TITLE
Link to current & previous versions broken

### ISSUE THREAD

**Issue by aarrowood** [apereo/phpCAS#279]
On the page:

   https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252517/phpCAS

the links to "Current Version" and "Browse all available versions" still point to the old developer.jasig.org server and no longer work.

**Comment by jfritschi** [comment]
I guess some the old wiki content has not survived the apereo move....

**Comment by jfritschi** [comment]
Fixed. But the wiki is only legacy and we will need to move the content.
