### ISSUE TITLE
I think should always use $_SERVER['HTTP_HOST']

### ISSUE THREAD

**Issue by fatindeed** [apereo/phpCAS#280]
https://github.com/apereo/phpCAS/blob/6846e000570bb4a82e72ea00ff1e5a2b0ac78c6f/source/CAS/Client.php#L3588-L3592

my nginx conf

> server {
>    listen      80 default_server;
>    server_name .mydomain.com;
>    ....
>}

then when I open `https://first.second.mydomain.com/`, `$_SERVER['SERVER_NAME']` will be `mydomain.com`, and `$_SERVER['HTTP_HOST']` will be `first.second.mydomain.com`.

**Comment by jfritschi** [comment]
Please have a look at #234. We already had some discussion in this topic.

Happy to hear your arguments aside from "make it work for my case" :-)

**Comment by jfritschi** [comment]
Closing this as duplicate
