### ISSUE TITLE
[1.3.6] bad tag

### ISSUE THREAD

**Issue by remicollet** [apereo/phpCAS#281]
Release 1.3.6 use ee912450f3efddde9238892e00e1b2cd2552e166

There is no diff with 1.3.5

```
diff -ru phpCAS-61c8899c8f91204e8b9135d795461e50fe5c2db0/source/CAS.php phpCAS-ee912450f3efddde9238892e00e1b2cd2552e166/source/CAS.php
--- phpCAS-61c8899c8f91204e8b9135d795461e50fe5c2db0/source/CAS.php	2017-04-10 21:12:45.000000000 +0200
+++ phpCAS-ee912450f3efddde9238892e00e1b2cd2552e166/source/CAS.php	2018-10-25 22:00:18.000000000 +0200
@@ -61,7 +61,7 @@
 /**
  * phpCAS version. accessible for the user by phpCAS::getVersion().
  */
-define('PHPCAS_VERSION', '1.3.5');
+define('PHPCAS_VERSION', '1.3.6');
 
 /**
  * @addtogroup public

```

Especially b44dacd84055ed0aec8513ce09629d2b0959dff3 is not included

I think the tag should be on 7972833e84f6ee5fa41f1479eab5d855109627f5

**Comment by remicollet** [comment]
As 1.3.6 is a security release, I think this issue is critical, as people relying on the tag will think to be secure, while still affected by the CVEs

**Comment by jfritschi** [comment]
I will Check later today. There were some issued during the release process.

Thanks for the info

**Comment by jfritschi** [comment]
Should be fixed now. There was an error during our release process that screwed up the tag..

Can you please verify? Thanks!

**Comment by remicollet** [comment]
LGTM
