### ISSUE TITLE
PEAR Package Link

### ISSUE THREAD

**Issue by pcfens** [apereo/phpCAS#282]
The links in [the documentation](https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252681/phpCAS+installation+guide) are broken, and we have a number of things that don't use composer.

Can a package can be made available (perhaps through [GitHub releases](https://help.github.com/articles/creating-releases/))?

Thanks!

**Comment by jtgasper3** [comment]
@pcfens: Can't speak for the download link, but you can build it locally (or with Docker) https://github.com/UniconLabs/dockerized-idp-testbed/blob/master/php-cas/Dockerfile#L3-L11

**Comment by jfritschi** [comment]
Releases are already available on github:

https://github.com/apereo/phpCAS/releases

Or is there any issues with the releases?

Documentation has to be updated since most of the jasig infrastructure dissapeared...

**Comment by jfritschi** [comment]
Install documentation is now updated. 

Have to review the wiki to identify any other old links.

**Comment by jfritschi** [comment]
@pcfens I would be happy to take a PR.

**Comment by pcfens** [comment]
Closing in favor of #297
