### ISSUE TITLE
Where is the API documentation?

### ISSUE THREAD

**Issue by adaugherity** [apereo/phpCAS#286]
[docs/index.html](https://github.com/apereo/phpCAS/blob/master/docs/index.html) refers to http://downloads.jasig.org/cas-clients/php/1.3.6/docs/api/ which is a 404, and I don't see any mention of API documentation at the [official phpCAS client page](https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252517/phpCAS), nor anywhere inside this repo.  BTW, where is docs/index.html hosted, anyway?  It's not what's displayed on the CASC wiki page; if it's not actually used anywhere, wouldn't a markdown or RST version be better, so GitHub would render it?

Searching DuckDuckGo yields 
http://developer.jasig.org/cas-clients/php/current/docs/api/classphpCAS.html which is also a 404, and Google finds nothing relevant except someone's old mirror of 1.0.x phpCAS API docs.  Perhaps the API docs on jasig.org were recently turned off?

Apologies if I'm missing something obvious.

**Comment by jfritschi** [comment]
You are absolutely right. Most of our stuff broke when the old jasig servers were retired. I have made some interim changes and the API docs can be found under:

https://apereo.github.io/phpCAS/
