### ISSUE TITLE
ticket failed and curl failed on different pc [CAS Authentication Failed]

### ISSUE THREAD

**Issue by mhanifahns** [apereo/phpCAS#294]
anyone know why my curl failed . and ticket failed but on my localserver in other pc its run without curl or ticket failed . And its failed too when iam running on server .

`C42E .START phpCAS-1.3.2 ****************** [CAS.php:450]
C42E .=> phpCAS::client('2.0', 'test.com', 443, '/casadfs') [login.php:37]
C42E .|    => CAS_Client::__construct('2.0', false, 'test.com', 443, '/casadfs', true) [CAS.php:347]
C42E .|    |    Starting a new session [Client.php:792]
C42E .|    |    Ticket 'ST-12155-knsp2uoAwAcPqyVAeNa7-test.com' found [Client.php:870]
C42E .|    <= ''
C42E .<= ''
C42E .=> phpCAS::setNoCasServerValidation() [login.php:39]
C42E .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1669]
C42E .<= ''
C42E .=> CAS_Client::handleLogoutRequests(true, false) [CAS.php:1299]
C42E .|    Not a logout request [Client.php:1469]
C42E .<= ''
C42E .=> phpCAS::forceAuthentication() [login.php:86]
C42E .|    => CAS_Client::forceAuthentication() [CAS.php:1101]
C42E .|    |    => CAS_Client::isAuthenticated() [Client.php:1083]
C42E .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1189]
C42E .|    |    |    |    no user found [Client.php:1375]
C42E .|    |    |    <= false
C42E .|    |    |    CAS 2.0 ticket `ST-12155-knsp2uoAwAcPqyVAeNa7-test.com' is present [Client.php:1223]
C42E .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL) [Client.php:1224]
C42E .|    |    |    |     [Client.php:2748]
C42E .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:2754]
C42E .|    |    |    |    |    => CAS_Client::getURL() [Client.php:417]
C42E .|    |    |    |    |    |    Final URI: http://localhost/test/trunk/src/app/login/admin [Client.php:3074]
C42E .|    |    |    |    |    <= 'http://localhost/test/trunk/src/app/login/admin'
C42E .|    |    |    |    <= 'https://test.com/casadfs/serviceValidate?service=http%3A%2F%2Flocalhost%2Ftest%2Ftrunk%2Fsrc%2Fapp%2Flogin%2Fadmin'
C42E .|    |    |    |    => CAS_Client::_readURL('https://test.com/casadfs/serviceValidate?service=http%3A%2F%2Flocalhost%2Ftest%2Ftrunk%2Fsrc%2Fapp%2Flogin%2Fadmin&ticket=ST-12155-knsp2uoAwAcPqyVAeNa7-test.com', NULL, NULL, NULL) [Client.php:2763]
C42E .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:220]
C42E .|    |    |    |    |    |    curl_exec() failed [CurlRequest.php:77]
C42E .|    |    |    |    |    <= false
C42E .|    |    |    |    <= false
C42E .|    |    |    |    could not open URL 'https://test.com/casadfs/serviceValidate?service=http%3A%2F%2Flocalhost%2Ftest%2Ftrunk%2Fsrc%2Fapp%2Flogin%2Fadmin&ticket=ST-12155-knsp2uoAwAcPqyVAeNa7-test.com' to validate (CURL error #7: Failed to connect to test.com port 80: Timed out) [Client.php:2766]
C42E .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://test.com/casadfs/serviceValidate?service=http%3A%2F%2Flocalhost%2Ftest%2Ftrunk%2Fsrc%2Fapp%2Flogin%2Fadmin&ticket=ST-12155-knsp2uoAwAcPqyVAeNa7-test.com', true) [Client.php:2770]
C42E .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
C42E .|    |    |    |    |    <= 'http://localhost/test/trunk/src/app/login/admin'
C42E .|    |    |    |    |    CAS URL: https://test.com/casadfs/serviceValidate?service=http%3A%2F%2Flocalhost%2Ftest%2Ftrunk%2Fsrc%2Fapp%2Flogin%2Fadmin&ticket=ST-12155-knsp2uoAwAcPqyVAeNa7-test.com [AuthenticationException.php:79]
C42E .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
C42E .|    |    |    |    |    Reason: no response from the CAS server [AuthenticationException.php:82]
C42E .|    |    |    |    |    exit()
C42E .|    |    |    |    |    -
C42E .|    |    |    |    -
C42E .|    |    |    -
C42E .|    |    -
C42E .|    -`

**Comment by jfritschi** [comment]
**could not open URL 'https://test.com/casadfs/serviceValidate?service=http%3A%2F%2Flocalhost%2Ftest%2Ftrunk%2Fsrc%2Fapp%2Flogin%2Fadmin&ticket=ST-12155-knsp2uoAwAcPqyVAeNa7-test.com' to validate (CURL error #7: Failed to connect to test.com port 80: Timed out) [Client.php:2766]**

This is the important line. You seem to have a connection error to the CAS server. It can be firewall, DNS or routing related (behind load balancer)...  Try connection to the URL from the commandline and debug from there.

**Comment by mhanifahns** [comment]
Thank you for your respond

iam sorry how to try connection to the URL from commandline?

is it ping ?

**Comment by jfritschi** [comment]
Yes, try working your way up. 

Try ping for IP and DNS. Then you can also use the curl command line tool to connect to the CAS server. (Use the URL that failed in the logs).

**Comment by mhanifahns** [comment]
it said unknown host . 
and why this CAS not working only in my server . and its run perfectly on my local ?

**Comment by jfritschi** [comment]
Then it's a network issue. Often times the webservers are behind a loadbalancer and have a different routing, DNS resolution or firewall config. 

Your issue sound like routing issues if the error is present when pinging the IP or a DNS issue when pinging the DNS name. The DNS can be worked around by a manual hosts entry.

All your issues are not related to phpcas and a network or server configuration related issues. You have to figure them out yourself or contact the responsible departments (server or network).
