### ISSUE TITLE
debug log will not write / create

### ISSUE THREAD

**Issue by jonycp** [apereo/phpCAS#295]
Hello,

I have searched and can't find this issue.  My error:

[20-Dec-2018 14:54:09 UTC] PHP Fatal error:  Uncaught CAS_AuthenticationException: CAS URL: https://cps92.quicklaunchsso.com/cas/serviceValidate?service=http*****
Authentication failure: Ticket not validated
Reason: no response from the CAS server in /web/weblibs/cas/CAS/Client.php:3195
Stack trace:
#0 /web/weblibs/cas/CAS/Client.php(1449): CAS_Client->validateCAS20('https://cps92.q...', '', NULL, false)
#1 /web/weblibs/cas/CAS/Client.php(1280): CAS_Client->isAuthenticated()
#2 /web/weblibs/cas/CAS.php(1098): CAS_Client->forceAuthentication()
#3 /var/www/html/timeclock/index.php(29): phpCAS::forceAuthentication()
#4 {main}
  thrown in /web/weblibs/cas/CAS/Client.php on line 3195

I have tried various forms of phpCAS::setDebug() - with and without filename, creating the file and modifying permissions open to world but nothing works to get the debug file.  I have also set phpCAS::setVerbose(true);

Please advise.
Thanks

**Comment by jfritschi** [comment]
Please check if your linux distribution is using something like PrivatTmp:
https://gryzli.info/2015/06/21/centos-7-missing-phpapache-temporary-files-in-tmp-systemd-private-temp/

**Comment by jonycp** [comment]
Thank you so much! However I am able to create file in /tmp freely.  No generated directory.   I am not the system admin but have sudo access, so I'm not sure if there's another process preventing updates to /tmp.   I will ask them to make sure.

Has there been any need to set /tmp permissions for the debug logging to function as intended?

Thanks

**Comment by jonycp** [comment]
I was informed by the system admin that your assertion appears to be correct.  caslog.txt was found at directories under /tmp.  We will pursue the reset the article recommends.
