### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by lrobinson33** [apereo/phpCAS#299]
I am not able to authenticate through CAS. I do receive a ticket. Please see log below.

E20F .START (2019-01-02 14:30:51) phpCAS-1.3.3+ ****************** [CAS.php:469]
E20F .=> phpCAS::client('S1', 'cas-test.gatech.edu', 443, '/cas') [auth.php:21]
E20F .|    => CAS_Client::__construct('S1', false, 'cas-test.gatech.edu', 443, '/cas', true) [CAS.php:360]
E20F .|    |    Starting a new session fvd66skrupea6ujv2hmi6eqia0 [Client.php:906]
E20F .|    <= ''
E20F .<= ''
E20F .=> phpCAS::setCasServerCACert('C:/apps/Apache24x32/htdocs/test/includes/login.gatech.edu.pem') [auth.php:25]
E20F .<= ''
E20F .=> phpCAS::setServerSamlValidateURL('https://cas-test.gatech.edu/cas/serviceValidate') [auth.php:34]
E20F .<= ''
E20F .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'cas-test5.gatech.edu',  1 => 'cas-test6.gatech.edu',)) [CAS.php:1258]
E20F .|    Not a logout request [Client.php:1701]
E20F .<= ''
E20F .=> phpCAS::forceAuthentication() [auth.php:43]
E20F .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
E20F .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
E20F .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
E20F .|    |    |    |    no user found [Client.php:1604]
E20F .|    |    |    <= false
E20F .|    |    |    no ticket found [Client.php:1463]
E20F .|    |    <= false
E20F .|    |    => CAS_Client::redirectToCas(false) [Client.php:1258]
E20F .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1625]
E20F .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
E20F .|    |    |    |    |    Final URI: https://sisapps-lrobinson33.gatech.edu/test/index.php [Client.php:3498]
E20F .|    |    |    |    <= 'https://sisapps-lrobinson33.gatech.edu/test/index.php'
E20F .|    |    |    <= 'https://cas-test.gatech.edu/cas/login?service=https%3A%2F%2Fsisapps-lrobinson33.gatech.edu%2Ftest%2Findex.php'
E20F .|    |    |    Redirect to : https://cas-test.gatech.edu/cas/login?service=https%3A%2F%2Fsisapps-lrobinson33.gatech.edu%2Ftest%2Findex.php [Client.php:1632]
E20F .|    |    |    exit()
E20F .|    |    |    -
E20F .|    |    -
E20F .|    -
FE09 .START (2019-01-02 14:31:26) phpCAS-1.3.3+ ****************** [CAS.php:469]
FE09 .=> phpCAS::client('S1', 'cas-test.gatech.edu', 443, '/cas') [auth.php:21]
FE09 .|    => CAS_Client::__construct('S1', false, 'cas-test.gatech.edu', 443, '/cas', true) [CAS.php:360]
FE09 .|    |    Starting a new session fvd66skrupea6ujv2hmi6eqia0 [Client.php:906]
FE09 .|    |    Ticket 'ST-7-ApsvEch2ZTiaghSCCiyE-cas-test5.gatech.edu' found [Client.php:989]
FE09 .|    <= ''
FE09 .<= ''
FE09 .=> phpCAS::setCasServerCACert('C:/apps/Apache24x32/htdocs/test/includes/login.gatech.edu.pem') [auth.php:25]
FE09 .<= ''
FE09 .=> phpCAS::setServerSamlValidateURL('https://cas-test.gatech.edu/cas/serviceValidate') [auth.php:34]
FE09 .<= ''
FE09 .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'cas-test5.gatech.edu',  1 => 'cas-test6.gatech.edu',)) [CAS.php:1258]
FE09 .|    Not a logout request [Client.php:1701]
FE09 .<= ''
FE09 .=> phpCAS::forceAuthentication() [auth.php:43]
FE09 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
FE09 .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
FE09 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
FE09 .|    |    |    |    no user found [Client.php:1604]
FE09 .|    |    |    <= false
FE09 .|    |    |    SAML 1.1 ticket `ST-7-ApsvEch2ZTiaghSCCiyE-cas-test5.gatech.edu' is present [Client.php:1444]
FE09 .|    |    |    => CAS_Client::validateSA('', NULL, NULL, false) [Client.php:1447]
FE09 .|    |    |    |    => CAS_Client::getServerSamlValidateURL() [Client.php:2028]
FE09 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:477]
FE09 .|    |    |    |    |    |    Final URI: https://sisapps-lrobinson33.gatech.edu/test/index.php [Client.php:3498]
FE09 .|    |    |    |    |    <= 'https://sisapps-lrobinson33.gatech.edu/test/index.php'
FE09 .|    |    |    |    <= 'https://cas-test.gatech.edu/cas/serviceValidate?TARGET=https%3A%2F%2Fsisapps-lrobinson33.gatech.edu%2Ftest%2Findex.php'
FE09 .|    |    |    |    => CAS_Client::_readURL('https://cas-test.gatech.edu/cas/serviceValidate?TARGET=https%3A%2F%2Fsisapps-lrobinson33.gatech.edu%2Ftest%2Findex.php', NULL, NULL, NULL) [Client.php:2036]
FE09 .|    |    |    |    |    => CAS_Client::_buildSAMLPayload() [Client.php:2781]
FE09 .|    |    |    |    |    <= '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol"  MajorVersion="1" MinorVersion="1" RequestID="_192.168.16.51.1024506224022" IssueInstant="2002-06-19T17:03:44.022Z"><samlp:AssertionArtifact>ST-7-ApsvEch2ZTiaghSCCiyE-cas-test5.gatech.edu</samlp:AssertionArtifact></samlp:Request></SOAP-ENV:Body></SOAP-ENV:Envelope>'
FE09 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
FE09 .|    |    |    |    |    |    CURL: Set CURLOPT_CAINFO C:/apps/Apache24x32/htdocs/test/includes/login.gatech.edu.pem [CurlRequest.php:129]
FE09 .|    |    |    |    |    |    Response Body: 
FE09 .|    |    |    |    |    |    
FE09 .|    |    |    |    |    |    
FE09 .|    |    |    |    |    |    
FE09 .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
FE09 .|    |    |    |    |    |    	<cas:authenticationFailure code='INVALID_REQUEST'>
FE09 .|    |    |    |    |    |    		&#039;service&#039; and &#039;ticket&#039; parameters are both required
FE09 .|    |    |    |    |    |    	</cas:authenticationFailure>
FE09 .|    |    |    |    |    |    </cas:serviceResponse>
FE09 .|    |    |    |    |    |    
FE09 .|    |    |    |    |    |     [CurlRequest.php:84]
FE09 .|    |    |    |    |    <= true
FE09 .|    |    |    |    <= true
FE09 .|    |    |    |    server version: S1 [Client.php:2045]
FE09 .|    |    |    |    bad XML root node (should be `Envelope' instead of `serviceResponse' [Client.php:2077]
FE09 .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'SA not validated', 'https://cas-test.gatech.edu/cas/serviceValidate?TARGET=https%3A%2F%2Fsisapps-lrobinson33.gatech.edu%2Ftest%2Findex.php', false, true, '<cas:serviceResponse xmlns:cas=\'http://www.yale.edu/tp/cas\'>	<cas:authenticationFailure code=\'INVALID_REQUEST\'>		&#039;service&#039; and &#039;ticket&#039; parameters are both required	</cas:authenticationFailure></cas:serviceResponse>') [Client.php:2082]
FE09 .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
FE09 .|    |    |    |    |    <= 'https://sisapps-lrobinson33.gatech.edu/test/index.php'
FE09 .|    |    |    |    |    CAS URL: https://cas-test.gatech.edu/cas/serviceValidate?TARGET=https%3A%2F%2Fsisapps-lrobinson33.gatech.edu%2Ftest%2Findex.php [AuthenticationException.php:79]
FE09 .|    |    |    |    |    Authentication failure: SA not validated [AuthenticationException.php:80]
FE09 .|    |    |    |    |    Reason: bad response from the CAS server [AuthenticationException.php:85]
FE09 .|    |    |    |    |    CAS response: 
FE09 .|    |    |    |    |    
FE09 .|    |    |    |    |    
FE09 .|    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
FE09 .|    |    |    |    |    	<cas:authenticationFailure code='INVALID_REQUEST'>
FE09 .|    |    |    |    |    		&#039;service&#039; and &#039;ticket&#039; parameters are both required
FE09 .|    |    |    |    |    	</cas:authenticationFailure>
FE09 .|    |    |    |    |    </cas:serviceResponse>
FE09 .|    |    |    |    |     [AuthenticationException.php:101]
FE09 .|    |    |    |    |    exit()
FE09 .|    |    |    |    |    -
FE09 .|    |    |    |    -
FE09 .|    |    |    -
FE09 .|    |    -
FE09 .|    -

**Comment by jfritschi** [comment]
You are using SAML mode and you have manually configured the wrong validation URL. Servicevalidate does not do SAML.

Please use our examples to debug your issues
