### ISSUE TITLE
Application not authorized to use CAS

### ISSUE THREAD

**Issue by Katabii** [apereo/phpCAS#300]
Hello,

I am trying to integrate this client with CAS version 6.0, and im getting this error "The application that you have tried to authenticate is not authorized to use CAS". It's possible to do this integration? How I could resolve this problem?

Thank you

**Comment by jfritschi** [comment]
Absolutely a server issue. The service registry is not properly configured.

**Comment by Katabii** [comment]
Thanks for the answers, I was able to solve the problem by configuring the server properties and service registry.

Now I can get the ldap attributes of the user except the name of the group he belongs to. I'm using CAS 6.0. How can I get this attribute? 

Thanks again for your time.

**Comment by jfritschi** [comment]
If your CAS server publishes user attributes (as the administrators or have a look at the debug log output and check for the full dump of the CAS server authentication answer) you can simply retrieve them:

https://github.com/apereo/phpCAS/blob/master/docs/examples/example_advanced_saml11.php

**Comment by Katabii** [comment]
All right, I've got everything going. I can finish the implementation with my services and applications at the moment.

Thank you very much for your help. Greetings.
