### ISSUE TITLE
example_simple.php throws HTTP ERROR 500 after login - Debian 8 Linux Server

### ISSUE THREAD

**Issue by emmachukwu** [apereo/phpCAS#305]
Dear All,
I am new to the phpCAS client. I just tried to run the example_simple.php on my project server (Debian 8 Linux hosted on AWS, Apache and PHP already configured and working correctly). 
It redirects as expected to the CAS login page but after authentication it throws  HTTP ERROR 500 instead of the Successful Login page.
I tried the same code with similar configuration on my shared hosting server (Hostgator) and it everything worked correctly. I have tried to figure out why it is not working on my project server without success. Please I need help.

![cas-successful](https://user-images.githubusercontent.com/8685484/54118438-52fdf600-43f3-11e9-9b61-c82748cf1599.PNG)

![cas-error](https://user-images.githubusercontent.com/8685484/54118148-ad4a8700-43f2-11e9-867f-d3af05d02bff.PNG)

**Comment by emmachukwu** [comment]
Resolved! I checked the error log and discovered it had to do with cURL. So I installed curl and php5-curl and the issue got resolved.

**Comment by phy25** [comment]
If you are all set please close the issue, thanks!
