### ISSUE TITLE
Failed to install phpcas through pear

### ISSUE THREAD

**Issue by hafriz** [apereo/phpCAS#307]
hi,

i try to install cas through pair but give install failed output. 

downloading 1.3.6 ...
Starting to download 1.3.6 (Unknown size)
.....done: 68,029 bytes
could not extract the package.xml file from "/tmp/pear/download/1.3.6"
Download of "https://github.com/apereo/phpCAS/archive/1.3.6.tar.gz" succeeded, but it is not a valid package archive
Invalid or missing remote package file
install failed

any guide? i also try to install older version if it will successfully install but output with same error

**Comment by jfritschi** [comment]
This issue has been fixed in #297 

We just need to cut a new release to make this work again.

**Comment by jfritschi** [comment]
I will try to do this in the next couple of days.

**Comment by hafriz** [comment]
hi @jfritschi thanks a lot, i'm wait for it. is there anyway i can install phpcas other than through pear?

**Comment by jfritschi** [comment]
I just cut a new release. Please check with version 1.3.7

**Comment by hafriz** [comment]
@jfritschi i have try to pear install.

> Starting to download 1.3.7 (Unknown size)
.............done: 68,327 bytes
could not extract the package.xml file from "/tmp/pear/download/1.3.7"
Download of "https://github.com/apereo/phpCAS/archive/1.3.7.tar.gz" succeeded, but it is not a valid package archive
Invalid or missing remote package file
install failed

**Comment by konfuzed** [comment]
@jfritschi Can you update that new release? 1.3.7 still has version 1.3.6 in its package.xml / release tarball even though the release shows 1.3.7.

**Comment by jfritschi** [comment]
Mmh, it seems the release logic is not working properly. I will need to debug what's causing the problem.

**Comment by jfritschi** [comment]
I have cut a new release and found the issue.

This link should work:
https://github.com/apereo/phpCAS/releases/download/1.3.8/CAS-1.3.8.tgz

**Comment by phy25** [comment]
Is this still an issue? Closing this but feel free to comment if it's still not working.

**Comment by dcpontius59** [comment]
I'm still seeing exactly this problem.  I inserted a tar -tvf into my Dockerfile so I could see what was in it, and the package.xml is missing from the tarball that it pulled, but I downloaded your tarball (above) and it's there.

Step 8/14 : RUN tar -tvf CAS-1.3.8.tgz && pear install CAS-1.3.8.tgz  && rm /CAS-1.3.8.tgz
 ---> Running in 242bd755a6a5
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/PGTStorage/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Http/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyChain/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/CAS/Request/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/docs/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/docs/examples/
drwxr-xr-x 0/0               0 2020-05-07 20:39 CAS-1.3.8/docs/images/
-rw-r--r-- 0/0           62187 2020-05-07 20:39 CAS-1.3.8/CAS.php
-rw-r--r-- 0/0            4396 2020-05-07 20:39 CAS-1.3.8/CAS/AuthenticationException.php
-rw-r--r-- 0/0            2631 2020-05-07 20:39 CAS-1.3.8/CAS/Autoload.php
-rw-r--r-- 0/0          141482 2020-05-07 20:39 CAS-1.3.8/CAS/Client.php
-rw-r--r-- 0/0           12243 2020-05-07 20:39 CAS-1.3.8/CAS/CookieJar.php
-rw-r--r-- 0/0            1982 2020-05-07 20:39 CAS-1.3.8/CAS/Exception.php
-rw-r--r-- 0/0            2932 2020-05-07 20:39 CAS-1.3.8/CAS/GracefullTerminationException.php
-rw-r--r-- 0/0            1515 2020-05-07 20:39 CAS-1.3.8/CAS/InvalidArgumentException.php
-rw-r--r-- 0/0            3259 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/Catalan.php
-rw-r--r-- 0/0            3260 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/ChineseSimplified.php
-rw-r--r-- 0/0            3230 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/English.php
-rw-r--r-- 0/0            3312 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/French.php
-rw-r--r-- 0/0            3270 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/German.php
-rw-r--r-- 0/0            3562 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/Greek.php
-rw-r--r-- 0/0            3349 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/Japanese.php
-rw-r--r-- 0/0            2610 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/LanguageInterface.php
-rw-r--r-- 0/0            3294 2020-05-07 20:39 CAS-1.3.8/CAS/Languages/Spanish.php
-rw-r--r-- 0/0            1925 2020-05-07 20:39 CAS-1.3.8/CAS/OutOfSequenceBeforeAuthenticationCallException.php
-rw-r--r-- 0/0            1981 2020-05-07 20:39 CAS-1.3.8/CAS/OutOfSequenceBeforeClientException.php
-rw-r--r-- 0/0            1936 2020-05-07 20:39 CAS-1.3.8/CAS/OutOfSequenceBeforeProxyException.php
-rw-r--r-- 0/0            1690 2020-05-07 20:39 CAS-1.3.8/CAS/OutOfSequenceException.php
-rw-r--r-- 0/0            6151 2020-05-07 20:39 CAS-1.3.8/CAS/PGTStorage/AbstractStorage.php
-rw-r--r-- 0/0           13046 2020-05-07 20:39 CAS-1.3.8/CAS/PGTStorage/Db.php
-rw-r--r-- 0/0            7814 2020-05-07 20:39 CAS-1.3.8/CAS/PGTStorage/File.php
-rw-r--r-- 0/0            2471 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService.php
-rw-r--r-- 0/0            4737 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Abstract.php
-rw-r--r-- 0/0            1511 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Exception.php
-rw-r--r-- 0/0            2880 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Http.php
-rw-r--r-- 0/0           10717 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Http/Abstract.php
-rw-r--r-- 0/0            3039 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Http/Get.php
-rw-r--r-- 0/0            4891 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Http/Post.php
-rw-r--r-- 0/0            8203 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Imap.php
-rw-r--r-- 0/0            2541 2020-05-07 20:39 CAS-1.3.8/CAS/ProxiedService/Testable.php
-rw-r--r-- 0/0            4354 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyChain.php
-rw-r--r-- 0/0            3555 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyChain/AllowedList.php
-rw-r--r-- 0/0            2108 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyChain/Any.php
-rw-r--r-- 0/0            1692 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyChain/Interface.php
-rw-r--r-- 0/0            1884 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyChain/Trusted.php
-rw-r--r-- 0/0            2313 2020-05-07 20:39 CAS-1.3.8/CAS/ProxyTicketException.php
-rw-r--r-- 0/0           10744 2020-05-07 20:39 CAS-1.3.8/CAS/Request/AbstractRequest.php
-rw-r--r-- 0/0            5090 2020-05-07 20:39 CAS-1.3.8/CAS/Request/CurlMultiRequest.php
-rw-r--r-- 0/0            6656 2020-05-07 20:39 CAS-1.3.8/CAS/Request/CurlRequest.php
-rw-r--r-- 0/0            1469 2020-05-07 20:39 CAS-1.3.8/CAS/Request/Exception.php
-rw-r--r-- 0/0            2867 2020-05-07 20:39 CAS-1.3.8/CAS/Request/MultiRequestInterface.php
-rw-r--r-- 0/0            5449 2020-05-07 20:39 CAS-1.3.8/CAS/Request/RequestInterface.php
-rw-r--r-- 0/0            2299 2020-05-07 20:39 CAS-1.3.8/CAS/TypeMismatchException.php
-rw-r--r-- 0/0           11357 2020-05-07 20:39 CAS-1.3.8/LICENSE
-rw-r--r-- 0/0            3914 2020-05-07 20:39 CAS-1.3.8/NOTICE
-rw-r--r-- 0/0            1078 2020-05-07 20:39 CAS-1.3.8/README.md
-rw-r--r-- 0/0            1390 2020-05-07 20:39 CAS-1.3.8/docs/Building
-rw-r--r-- 0/0           24842 2020-05-07 20:39 CAS-1.3.8/docs/ChangeLog
-rw-r--r-- 0/0            4675 2020-05-07 20:39 CAS-1.3.8/docs/Upgrading
-rw-r--r-- 0/0            3470 2020-05-07 20:39 CAS-1.3.8/docs/examples/config.example.php
-rw-r--r-- 0/0            1516 2020-05-07 20:39 CAS-1.3.8/docs/examples/create_pgt_storage_db_table.php
-rw-r--r-- 0/0             143 2020-05-07 20:39 CAS-1.3.8/docs/examples/example.css
-rw-r--r-- 0/0            2400 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_advanced_saml11.php
-rw-r--r-- 0/0            2470 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_custom_urls.php
-rw-r--r-- 0/0            2006 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_gateway.php
-rw-r--r-- 0/0            2568 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_hardening.php
-rw-r--r-- 0/0            2098 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_html.php
-rw-r--r-- 0/0            1989 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_lang.php
-rw-r--r-- 0/0            2026 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_logout.php
-rw-r--r-- 0/0            2147 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_no_ssl_cn_validation.php
-rw-r--r-- 0/0            2370 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_pgt_storage_db.php
-rw-r--r-- 0/0            2292 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_pgt_storage_file.php
-rw-r--r-- 0/0            3315 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_proxy_GET.php
-rw-r--r-- 0/0            3536 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_proxy_POST.php
-rw-r--r-- 0/0            1946 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_proxy_rebroadcast.php
-rw-r--r-- 0/0            2199 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_proxy_serviceWeb.php
-rw-r--r-- 0/0            2178 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_proxy_serviceWeb_chaining.php
-rw-r--r-- 0/0            2116 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_renew.php
-rw-r--r-- 0/0            3629 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_service.php
-rw-r--r-- 0/0            3932 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_service_POST.php
-rw-r--r-- 0/0            3811 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_service_that_proxies.php
-rw-r--r-- 0/0            1871 2020-05-07 20:39 CAS-1.3.8/docs/examples/example_simple.php
-rw-r--r-- 0/0             794 2020-05-07 20:39 CAS-1.3.8/docs/examples/script_info.php
-rw-r--r-- 0/0            2621 2020-05-07 20:39 CAS-1.3.8/docs/images/esup-portail.png
-rw-r--r-- 0/0            2384 2020-05-07 20:39 CAS-1.3.8/docs/images/jasig.png
-rw-r--r-- 0/0            6771 2020-05-07 20:39 CAS-1.3.8/docs/images/phpcas.png
-rw-r--r-- 0/0             866 2020-05-07 20:39 CAS-1.3.8/docs/index.html
could not extract the package.xml file from "CAS-1.3.8.tgz"
install failed
The command '/bin/sh -c tar -tvf CAS-1.3.8.tgz && pear install CAS-1.3.8.tgz  && rm /CAS-1.3.8.tgz' returned a non-zero code: 1

**Comment by phy25** [comment]
@dcpontius59  What instruction are you following? Could you post a link if any?

The "archive" link does not work because it's simply GitHub's master branch without the xml, while the release asset in https://github.com/apereo/phpCAS/releases (https://github.com/apereo/phpCAS/releases/download/1.3.8/CAS-1.3.8.tgz for 1.3.8) should work.

(Also for some reason GitHub/AWS banned my request on the playground machine, and I have to manually `curl` the file for installation.)

**Comment by adaugherity** [comment]
> The "archive" link does not work because it's simply GitHub's master branch without the xml, while the release asset in https://github.com/apereo/phpCAS/releases [...] should work.
>
> (Also for some reason GitHub/AWS banned my request on the playground machine, and I have to manually curl the file for installation.)

Thanks for that @phy25!  For anyone else encountering this:
- Only the **CAS-1.x.y.tgz** release tarballs contain the package.xml file needed by PEAR; the "source code" **1.x.y.tar.gz** (or .zip) tarballs do not.
- For some reason GitHub bans directly installing via PEAR, e.g.:
> $ sudo pear install https://github.com/apereo/phpCAS/releases/download/1.4.0/CAS-1.4.0.tgz
Could not download from "https://github.com/apereo/phpCAS/releases/download/1.4.0/CAS-1.4.0.tgz" (File https://github-releases.githubusercontent.com:443/2352781/aa830a80-c193-11eb-92a9-1764a6b7da3f not valid (received: HTTP/1.1 403 Forbidden
))
Invalid or missing remote package file
install failed

   **However, fetching that file with curl or wget and then `pear install ./CAS-1.4.0.tgz` works fine.**  What's confusing is that GitHub does _not_ give the 403 when trying to `pear install` the "source code" archives, but those don't work with PEAR.  What a confusing, backwards situation!
- The [installation page](https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252681/phpCAS+installation+guide) in the wiki not only refers to an outdated version, but lists `pear install` commands for the source archives which lack the package.xml.  Additionally, the "browse all versions" link is 404.

   Can a bot update the wiki page with each release?
