### ISSUE TITLE
I have a phpcas confused

### ISSUE THREAD

**Issue by wg2931** [apereo/phpCAS#309]
17FAD .START phpCAS-1.3.2+ ****************** [CAS.php:434]
7FAD .=> phpCAS::client('2.0', '192.168.60.122', 80, 'dsssoserver') [Login.php:71]
7FAD .|    => CAS_Client::__construct('2.0', false, '192.168.60.122', 80, 'dsssoserver', true) [CAS.php:336]
7FAD .|    |    Ticket 'ST-62-rodUyaiUxVX4q3JNONwx-dsssoserver' found [Client.php:980]
7FAD .|    <= ''
7FAD .<= ''
7FAD .=> phpCAS::setNoCasServerValidation() [Login.php:72]
7FAD .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1551]
7FAD .<= ''
7FAD .=> CAS_Client::handleLogoutRequests(true, false) [CAS.php:1190]
7FAD .|    Not a logout request [Client.php:1687]
7FAD .<= ''
7FAD .=> phpCAS::forceAuthentication() [Login.php:74]
7FAD .|    => CAS_Client::forceAuthentication() [CAS.php:1011]
7FAD .|    |    => CAS_Client::isAuthenticated() [Client.php:1238]
7FAD .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1351]
7FAD .|    |    |    |    no user found [Client.php:1586]
7FAD .|    |    |    <= false
7FAD .|    |    |    CAS 2.0 ticket `ST-62-rodUyaiUxVX4q3JNONwx-dsssoserver' is present [Client.php:1400]
7FAD .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL) [Client.php:1403]
7FAD .|    |    |    |     [Client.php:3111]
7FAD .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3118]
7FAD .|    |    |    |    |    => CAS_Client::getURL() [Client.php:449]
7FAD .|    |    |    |    |    |    Final URI: http://localhost:8081/server/zhijiaomofang/api/login/cas [Client.php:3476]
7FAD .|    |    |    |    |    <= 'http://localhost:8081/server/zhijiaomofang/api/login/cas'
7FAD .|    |    |    |    <= 'http://192.168.60.122:80/dsssoserver/serviceValidate?service=http%3A%2F%2Flocalhost%3A8081%2Fserver%2Fzhijiaomofang%2Fapi%2Flogin%2Fcas'
7FAD .|    |    |    |    => CAS_Client::_readURL('http://192.168.60.122:80/dsssoserver/serviceValidate?service=http%3A%2F%2Flocalhost%3A8081%2Fserver%2Fzhijiaomofang%2Fapi%2Flogin%2Fcas&ticket=ST-62-rodUyaiUxVX4q3JNONwx-dsssoserver', NULL, NULL, NULL) [Client.php:3128]
7FAD .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
7FAD .|    |    |    |    |    |    Response Body: 
7FAD .|    |    |    |    |    |    
7FAD .|    |    |    |    |    |    
7FAD .|    |    |    |    |    |    
7FAD .|    |    |    |    |    |    
7FAD .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
7FAD .|    |    |    |    |    |    	<cas:authenticationFailure code='Service not allowed to validate tickets.'>
7FAD .|    |    |    |    |    |    		Service not allowed to validate tickets.
7FAD .|    |    |    |    |    |    	</cas:authenticationFailure>
7FAD .|    |    |    |    |    |    </cas:serviceResponse>
7FAD .|    |    |    |    |    |    
7FAD .|    |    |    |    |    |     [CurlRequest.php:84]
7FAD .|    |    |    |    |    <= true
7FAD .|    |    |    |    <= true
7FAD .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'http://192.168.60.122:80/dsssoserver/serviceValidate?service=http%3A%2F%2Flocalhost%3A8081%2Fserver%2Fzhijiaomofang%2Fapi%2Flogin%2Fcas&ticket=ST-62-rodUyaiUxVX4q3JNONwx-dsssoserver', false, false, '<cas:serviceResponse xmlns:cas=\'http://www.yale.edu/tp/cas\'>	<cas:authenticationFailure code=\'Service not allowed to validate tickets.\'>		Service not allowed to validate tickets.	</cas:authenticationFailure></cas:serviceResponse>', 'Service not allowed to validate tickets.', 'Service not allowed to validate tickets.') [Client.php:3219]
7FAD .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
7FAD .|    |    |    |    |    <= 'http://localhost:8081/server/zhijiaomofang/api/login/cas'
7FAD .|    |    |    |    |    CAS URL: http://192.168.60.122:80/dsssoserver/serviceValidate?service=http%3A%2F%2Flocalhost%3A8081%2Fserver%2Fzhijiaomofang%2Fapi%2Flogin%2Fcas&ticket=ST-62-rodUyaiUxVX4q3JNONwx-dsssoserver [AuthenticationException.php:79]
7FAD .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
7FAD .|    |    |    |    |    Reason: [Service not allowed to validate tickets.] CAS error: Service not allowed to validate tickets. [AuthenticationException.php:95]
7FAD .|    |    |    |    |    CAS response: 
7FAD .|    |    |    |    |    
7FAD .|    |    |    |    |    
7FAD .|    |    |    |    |    
7FAD .|    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
7FAD .|    |    |    |    |    	<cas:authenticationFailure code='Service not allowed to validate tickets.'>
7FAD .|    |    |    |    |    		Service not allowed to validate tickets.
7FAD .|    |    |    |    |    	</cas:authenticationFailure>
7FAD .|    |    |    |    |    </cas:serviceResponse>
7FAD .|    |    |    |    |     [AuthenticationException.php:100]
7FAD .|    |    |    |    |    exit()
7FAD .|    |    |    |    |    -
7FAD .|    |    |    |    -
7FAD .|    |    |    -
7FAD .|    |    -
7FAD .|    -

**Comment by jfritschi** [comment]
The CAS server says:

Service not allowed to validate tickets.

You have to adds your URL to the CAS server registry. This is not a phpCAS issue.

Btw. your phpCAS client is outdated.
