### ISSUE TITLE
AuthenticationException UNAUTHORIZED_SERVICE

### ISSUE THREAD

**Issue by g-geffroy** [apereo/phpCAS#310]
Dear all,

I'm testing the authentication on my client CAS server using CAS2.
The serviceValidate failed to re-validate the given ticket, but I don't understand this issue. Do you have any idea of the problem ?
I've no choice but using port 80 to connect to CAS server, but I don't think it's the problem here. 

8B3C .START (2019-06-13 10:23:52) phpCAS-1.3.7 ****************** [CAS.php:475]
8B3C .=> phpCAS::client('2.0', 'www.myclient.com', 80, '/casController') [jsso.php:98]
8B3C .|    => CAS_Client::__construct('2.0', false, 'www.myclient.com', 80, '/casController', true) [CAS.php:366]
8B3C .|    |    Starting a new session 43qcqi0ik8iei4gfq10li46k7l [Client.php:934]
8B3C .|    |    Session is not authenticated [Client.php:940]
8B3C .|    |    Ticket 'ERA-5d01fbb9a00f2-51e2e0ea23444cf377552b95daa7dc10' found [Client.php:1018]
8B3C .|    <= ''
8B3C .<= ''
8B3C .=> phpCAS::setNoCasServerValidation() [jsso.php:105]
8B3C .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
8B3C .<= ''
8B3C .=> phpCAS::forceAuthentication() [jsso.php:107]
8B3C .|    => CAS_Client::forceAuthentication() [CAS.php:1120]
8B3C .|    |    => CAS_Client::isAuthenticated() [Client.php:1278]
8B3C .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1390]
8B3C .|    |    |    |    no user found [Client.php:1632]
8B3C .|    |    |    <= false
8B3C .|    |    |    CAS 2.0 ticket `ERA-5d01fbb9a00f2-51e2e0ea23444cf377552b95daa7dc10' is present [Client.php:1443]
8B3C .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1446]
8B3C .|    |    |    |     [Client.php:3163]
8B3C .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3169]
8B3C .|    |    |    |    |    => CAS_Client::getURL() [Client.php:455]
8B3C .|    |    |    |    |    |    Final URI: http://myserver.local/connexion [Client.php:3532]
8B3C .|    |    |    |    |    <= 'http://myserver.local/connexion'
8B3C .|    |    |    |    <= 'http://www.myclient.com:80/casController/serviceValidate?service=http%3A%2F%2Fmyserver.local%2Fconnexion'
8B3C .|    |    |    |    => CAS_Client::_readURL('http://www.myclient.com:80/casController/serviceValidate?service=http%3A%2F%2Fmyserver.local%2Fconnexion&ticket=ERA-5d01fbb9a00f2-51e2e0ea23444cf377552b95daa7dc10', NULL, NULL, NULL) [Client.php:3184]
8B3C .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
8B3C .|    |    |    |    |    |    Response Body: 
8B3C .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
8B3C .|    |    |    |    |    |        <cas:authenticationFailure code="UNAUTHORIZED_SERVICE">
8B3C .|    |    |    |    |    |            Auth error for service http://myserver.local/connexion    </cas:authenticationFailure>
8B3C .|    |    |    |    |    |    </cas:serviceResponse>
8B3C .|    |    |    |    |    |     [CurlRequest.php:84]
8B3C .|    |    |    |    |    <= true
8B3C .|    |    |    |    <= true
8B3C .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'http://www.myclient.com:80/casController/serviceValidate?service=http%3A%2F%2Fmyserver.local%2Fconnexion&ticket=ERA-5d01fbb9a00f2-51e2e0ea23444cf377552b95daa7dc10', false, false, '<cas:serviceResponse xmlns:cas=\'http://www.yale.edu/tp/cas\'>    <cas:authenticationFailure code="UNAUTHORIZED_SERVICE">        Auth error for service http://myserver.local/connexion    </cas:authenticationFailure></cas:serviceResponse>', 'UNAUTHORIZED_SERVICE', 'Auth error for service http://myserver.local/connexion') [Client.php:3230]
8B3C .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:77]
8B3C .|    |    |    |    |    <= 'http://myserver.local/connexion'
8B3C .|    |    |    |    |    CAS URL: http://www.myclient.com:80/casController/serviceValidate?service=http%3A%2F%2Fmyserver.local%2Fconnexion&ticket=ERA-5d01fbb9a00f2-51e2e0ea23444cf377552b95daa7dc10 [AuthenticationException.php:80]
8B3C .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:81]
8B3C .|    |    |    |    |    Reason: [UNAUTHORIZED_SERVICE] CAS error: Auth error for service http://myserver.local/connexion [AuthenticationException.php:97]
8B3C .|    |    |    |    |    CAS response: <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
8B3C .|    |    |    |    |        <cas:authenticationFailure code="UNAUTHORIZED_SERVICE">
8B3C .|    |    |    |    |            Auth error for service http://myserver.local/connexion    </cas:authenticationFailure>
8B3C .|    |    |    |    |    </cas:serviceResponse> [AuthenticationException.php:102]
8B3C .|    |    |    |    |    exit()
8B3C .|    |    |    |    |    -
8B3C .|    |    |    |    -
8B3C .|    |    |    -
8B3C .|    |    -
8B3C .|    -

Thank you

**Comment by jfritschi** [comment]
This is a CAS server side issue. You have to configure which services aka URLs are allowed to use cas. This is done through the CAS server side service registry: https://apereo.github.io/cas/6.0.x/services/Service-Management.html

**Comment by g-geffroy** [comment]
Thank you ! I handle this point with my client.
