### ISSUE TITLE
Redirect you too many times when using PHP 7 =>

### ISSUE THREAD

**Issue by adisnabawi** [apereo/phpCAS#313]
ERR_TOO_MANY_REDIRECT happen when upgrading to php7. It's working fine in php5.6.
The log as below:

   |    Starting a new session  [Client.php:932]
34C3 .|    |    Session is not authenticated [Client.php:938]
34C3 .|    <= ''
34C3 .<= ''
34C3 .=> phpCAS::setNoCasServerValidation() [authenticated.php:33]
34C3 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
34C3 .<= ''
34C3 .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'cas-real-1.example.com',  1 => 'cas-real-2.example.com',)) [CAS.php:1298]
34C3 .|    Not a logout request [Client.php:1744]
34C3 .<= ''
34C3 .=> phpCAS::forceAuthentication() [authenticated.php:46]
34C3 .|    => CAS_Client::forceAuthentication() [CAS.php:1120]
34C3 .|    |    => CAS_Client::isAuthenticated() [Client.php:1286]
34C3 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1398]
34C3 .|    |    |    |    no user found [Client.php:1640]
34C3 .|    |    |    <= false
34C3 .|    |    |    no ticket found [Client.php:1499]
34C3 .|    |    <= false
34C3 .|

**Comment by jfritschi** [comment]
The log contains only a single session and does not even show the redirect. There is no way to debug this with only this log snippet...

Most likely it has to do with your session management. Please check that session management works on your php installation.

**Comment by jfritschi** [comment]
Please use one of our simple examples that we ship with phpcas for debugging.

**Comment by adisnabawi** [comment]
Thanks @jfitschi. Turn out, the problem with the php session😅. It not able to write the session. Thats why it keep creating new session and redirect happen. I change the tmp folder permission and finally it works 😄
