### ISSUE TITLE
Warning: Unexpected character input

### ISSUE THREAD

**Issue by jamac** [apereo/phpCAS#314]
https://github.com/apereo/phpCAS/blob/ff165bf94c62b4cb76c5eebd3ea3d157c24e527c/source/CAS.php#L1877

**Warning:** Unexpected character in input: '\\' (ASCII=92) state=1 in **/web/staging/CAS/CAS-1.3.8/CAS.php** on line **1877**

I must be the only poor schmuck required to run this on PHP 5.2. Is `\CAS_Client` required? or would `CAS_Client` suffice?

I know it's just a warning, but that warning is interfering with the redirect to our login page.

If I remove the `\` everything appears fine, but I honestly can't say I know what all the ramifications are.

If I `grep -FRi "(\\CAS"` the repo this is the only instance I can find (excluding ./docs)

**Comment by jfritschi** [comment]
The slash was introduced with php namespacing in php 5.3 
https://www.php.net/manual/de/language.namespaces.importing.php

Removing it should make no difference for you.

**Comment by phy25** [comment]
Closing since:
https://github.com/apereo/phpCAS/blob/ff165bf94c62b4cb76c5eebd3ea3d157c24e527c/composer.json#L13

**Comment by jamac** [comment]
Trying reply by email.

Super. Thanks for the help.

________________________________
