### ISSUE TITLE
attribute parsing mangles name and value in jasig-style attributes

### ISSUE THREAD

**Issue by ts23** [apereo/phpCAS#316]
Our CAS server submits the attributes in a slightly different layout to the styles parsed in the phpCAS client. As the client does no complete XML parsing it merges the attribute name and value. 

the Server response in our case is:

```
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
  <cas:authenticationSuccess>
    <cas:user>jsmith</cas:user>
    <cas:attributes>
      <cas:attribute>
        <cas:name>surname</cas:name>
        <cas:value>Smith</cas:value>
      </cas:attribute>
      <cas:attribute>
        <cas:name>givenName</cas:name>
        <cas:value>John</cas:value>
      </cas:attribute>
      <cas:attribute>
        <cas:name>memberOf</cas:name>
        <cas:value>['CN=Staff,OU=Groups,DC=example,DC=edu', 'CN=Spanish Department,OU=Departments,OU=Groups,DC=example,DC=edu']</cas:value>
      </cas:attribute>
    </cas:attributes>
    <cas:proxyGrantingTicket>PGTIOU-84678-8a9d2sfa23casd</cas:proxyGrantingTicket>
  </cas:authenticationSuccess>
</cas:serviceResponse>
```

the output of the standard parsing using `print_r()` is:

```
Array
(
    [attribute] => Array
        (
            [0] => surnameSmith
            [1] => givenNameJohn
            [2] => memberOf['CN=Staff,OU=Groups,DC=example,DC=edu', 'CN=Spanish Department,OU=Departments,OU=Groups,DC=example,DC=edu']
        )
)
```

**Comment by jfritschi** [comment]
Not sure what CAS server you are using...We are alread supporting 3 types of custom attribute release:
https://github.com/apereo/phpCAS/blob/95f75110466bfd442905f9a8be4b79da3f86eaff/source/CAS/Client.php#L3349

I suggest you either test using SAML_VERSION_1_1 attribute release (which is standardized) or extend the existing attribute parsing (not sure this is really sensible to do these custom extension of the CAS protocol)

**Comment by ts23** [comment]
I was looking at extending the existing attribute parsing possibly replacing it with a full xml-parser as our version is nothing but another way of writing the XML.

**Comment by jfritschi** [comment]
We have always stayed away from introducing a dependency for a full xml library. We are really trying to keep phpcas small without much dependencies...

**Comment by ts23** [comment]
I haven't put a full XML lib in, I just did a bit more recursive parsing
