### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by nathanczachur** [apereo/phpCAS#318]
Hey,

I am having a problem with the certificate I am using for SSL, I get this error:
> CURL error #60: SSL certificate problem: self signed certificate in certificate chain

So, the certificate I am using is from my production application, but I cannot use it for my staging application is using a different domain.

I have been told to use a self-signed cert or something else for this, however I don't know how to generate this. Does anyone have any advice?

Thanks in advance!

**Comment by jfritschi** [comment]
You should disable certifcate validation. This is a usefull feature for testing purposes...

phpCAS::setNoCasServerValidation();

**Comment by phy25** [comment]
If you still want to use a self-signed cert for your production app (this error is complaining that a self-signed one is in use), you may want to look at `phpCAS::setCasServerCACert()` to properly validate your cert.

Ref: https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html

**Comment by nathanczachur** [comment]
Thanks for the advice guys!

@jfritschi even though it's a testing environment, I would still like to use the SSL certificate as its on the internet.

@phy25 I am already using phpCAS::setCasServerCACert(), but the certificate was wrong. I was using a CA signed certificate, but for the wrong CN (Common Name).

I think I am going to have to generate my own certificiate with Let's Encrypt as the CA and use that instead. Fingers crossed it works!

Thanks again!
