### ISSUE TITLE
when in ie browser , session_id() always diffenrent, so id loop login

### ISSUE THREAD

**Issue by lpx20000** [apereo/phpCAS#319]
here are the debug log, session_id every time is different, but first time it validate is ok , and when redirect the session_id is change, but ticket is present, so it's unalbe to recognized , becaset it had been validated, so pl help me, i just can figure out the session change , and in chrome, firfox it's ok to login and the login log is ok , just on ie explore browser 11 , it's not, and i need to login on ie:

`DAC0 .START (2019-10-18 14:15:19) phpCAS-1.3.7 ****************** [CAS.php:475]
DAC0 .Loaded configuration:
DAC0 .a:20:{s:12:"cas_hostname";s:14:"myshost";s:14:"cas_real_hosts";s:14:"myshost";s:16:"cas_session_name";s:7:"CASAuth";s:19:"cas_control_session";b:0;s:9:"cas_proxy";b:0;s:8:"cas_port";i:443;s:7:"cas_uri";s:4:"/cas";s:14:"cas_validation";s:0:"";s:8:"cas_cert";s:0:"";s:15:"cas_validate_cn";b:1;s:13:"cas_login_url";s:0:"";s:14:"cas_logout_url";s:65:"http://myshost/cas/logout?service=http://app.com";s:19:"cas_logout_redirect";s:0:"";s:17:"cas_redirect_path";s:30:"http://uatapp.com/";s:15:"cas_enable_saml";b:0;s:11:"cas_version";s:3:"2.0";s:9:"cas_debug";b:1;s:18:"cas_verbose_errors";b:1;s:14:"cas_masquerade";s:0:"";s:20:"cas_session_lifetime";i:120;}
DAC0 .=> phpCAS::client('2.0', 'myshost', 443, '/cas', false) [CasManager.php:93]
DAC0 .|    => CAS_Client::__construct('2.0', false, 'myshost', 443, '/cas', false) [CAS.php:366]
DAC0 .|    |    Starting a new session rm8gkjd39i2c7agl6m2d3nfma6 [Client.php:933]
DAC0 .|    |    Session is not authenticated [Client.php:939]
DAC0 .|    <= ''
DAC0 .<= ''
DAC0 .=> phpCAS::setNoCasServerValidation() [CasManager.php:151]
DAC0 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
DAC0 .<= ''
DAC0 .=> phpCAS::setServerLoginURL('') [CasManager.php:52]
DAC0 .<= ''
DAC0 .=> phpCAS::setFixedServiceURL('http://uatapp.com/') [CasManager.php:56]
DAC0 .<= ''
DAC0 .=> phpCAS::setServerLogoutURL('http://myshost/cas/logout?service=http://app.com') [CasManager.php:59]
DAC0 .<= ''
DAC0 .=> phpCAS::checkAuthentication() [CasManager.php:293]
DAC0 .|    => CAS_Client::checkAuthentication() [CAS.php:1100]
DAC0 .|    |    => CAS_Client::isAuthenticated() [Client.php:1326]
DAC0 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1388]
DAC0 .|    |    |    |    no user found [Client.php:1630]
DAC0 .|    |    |    <= false
DAC0 .|    |    |    no ticket found [Client.php:1489]
DAC0 .|    |    <= false
DAC0 .|    |    user is not authenticated (cache reset) [Client.php:1364]
DAC0 .|    |    => CAS_Client::redirectToCas(true) [Client.php:1365]
DAC0 .|    |    |    => CAS_Client::getServerLoginURL(true, false) [Client.php:1651]
DAC0 .|    |    |    |    => CAS_Client::getURL() [Client.php:343]
DAC0 .|    |    |    |    <= 'http://uatapp.com/'
DAC0 .|    |    |    <= 'http://myshost/cas/login?service=http%3A%2F%2Fuatapp.com%2F&gateway=true'
DAC0 .|    |    |    Redirect to : http://myshost/cas/login?service=http%3A%2F%2Fuatapp.com%2F&gateway=true [Client.php:1658]
DAC0 .|    |    |    exit()
DAC0 .|    |    |    -
DAC0 .|    |    -
DAC0 .|    -
49F3 .START (2019-10-18 14:15:19) phpCAS-1.3.7 ****************** [CAS.php:475]
49F3 .Loaded configuration:
49F3 .a:20:{s:12:"cas_hostname";s:14:"myshost";s:14:"cas_real_hosts";s:14:"myshost";s:16:"cas_session_name";s:7:"CASAuth";s:19:"cas_control_session";b:0;s:9:"cas_proxy";b:0;s:8:"cas_port";i:443;s:7:"cas_uri";s:4:"/cas";s:14:"cas_validation";s:0:"";s:8:"cas_cert";s:0:"";s:15:"cas_validate_cn";b:1;s:13:"cas_login_url";s:0:"";s:14:"cas_logout_url";s:65:"http://myshost/cas/logout?service=http://app.com";s:19:"cas_logout_redirect";s:0:"";s:17:"cas_redirect_path";s:30:"http://uatapp.com/";s:15:"cas_enable_saml";b:0;s:11:"cas_version";s:3:"2.0";s:9:"cas_debug";b:1;s:18:"cas_verbose_errors";b:1;s:14:"cas_masquerade";s:0:"";s:20:"cas_session_lifetime";i:120;}
49F3 .=> phpCAS::client('2.0', 'myshost', 443, '/cas', false) [CasManager.php:93]
49F3 .|    => CAS_Client::__construct('2.0', false, 'myshost', 443, '/cas', false) [CAS.php:366]
49F3 .|    |    Starting a new session atn8o44a8rblm805ijccf5ubqk [Client.php:933]
49F3 .|    |    Session is not authenticated [Client.php:939]
49F3 .|    |    Ticket 'ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org' found [Client.php:1016]
49F3 .|    <= ''
49F3 .<= ''
49F3 .=> phpCAS::setNoCasServerValidation() [CasManager.php:151]
49F3 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
49F3 .<= ''
49F3 .=> phpCAS::setServerLoginURL('') [CasManager.php:52]
49F3 .<= ''
49F3 .=> phpCAS::setFixedServiceURL('http://uatapp.com/') [CasManager.php:56]
49F3 .<= ''
49F3 .=> phpCAS::setServerLogoutURL('http://myshost/cas/logout?service=http://app.com') [CasManager.php:59]
49F3 .<= ''
49F3 .=> phpCAS::checkAuthentication() [CasManager.php:293]
49F3 .|    => CAS_Client::checkAuthentication() [CAS.php:1100]
49F3 .|    |    => CAS_Client::isAuthenticated() [Client.php:1326]
49F3 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1388]
49F3 .|    |    |    |    no user found [Client.php:1630]
49F3 .|    |    |    <= false
49F3 .|    |    |    CAS 2.0 ticket `ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org' is present [Client.php:1441]
49F3 .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1444]
49F3 .|    |    |    |     [Client.php:3160]
49F3 .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3166]
49F3 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:454]
49F3 .|    |    |    |    |    <= 'http://uatapp.com/'
49F3 .|    |    |    |    <= 'http://myshost/cas/serviceValidate?service=http%3A%2F%2Fuatapp.com%2F'
49F3 .|    |    |    |    => CAS_Client::_readURL('http://myshost/cas/serviceValidate?service=http%3A%2F%2Fuatapp.com%2F&ticket=ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org', NULL, NULL, NULL) [Client.php:3181]
49F3 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
49F3 .|    |    |    |    |    |    Response Body:
49F3 .|    |    |    |    |    |
49F3 .|    |    |    |    |    |
49F3 .|    |    |    |    |    |
49F3 .|    |    |    |    |    |
49F3 .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    49F3 .|    |    |    |    |    |    	<cas:authenticationSuccess>
        49F3 .|    |    |    |    |    |    		<cas:user>admin1</cas:user>
        49F3 .|    |    |    |    |    |
        49F3 .|    |    |    |    |    |
        49F3 .|    |    |    |    |    |    	</cas:authenticationSuccess>
    49F3 .|    |    |    |    |    |    </cas:serviceResponse>
49F3 .|    |    |    |    |    |     [CurlRequest.php:84]
49F3 .|    |    |    |    |    <= true
49F3 .|    |    |    |    <= true
49F3 .|    |    |    |    => CAS_Client::_readExtraAttributesCas20(DOMNodeList) [Client.php:3245]
49F3 .|    |    |    |    |    Testing for rubycas style attributes [Client.php:3358]
49F3 .|    |    |    |    <= ''
49F3 .|    |    |    |    => CAS_ProxyChain_AllowedList::isProxyListAllowed(array ()) [Client.php:3257]
49F3 .|    |    |    |    |    No proxies were found in the response [AllowedList.php:81]
49F3 .|    |    |    |    <= true
49F3 .|    |    |    |    => CAS_Client::_renameSession('ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org') [Client.php:3275]
49F3 .|    |    |    |    |    Skipping session rename since phpCAS is not handling the session. [Client.php:3678]
49F3 .|    |    |    |    <= ''
49F3 .|    |    |    <= true
49F3 .|    |    |    CAS 2.0 ticket `ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org' was validated [Client.php:1447]
49F3 .|    |    |    => CAS_Client::getURL() [Client.php:1513]
49F3 .|    |    |    <= 'http://uatapp.com/'
49F3 .|    |    |    Prepare redirect to : http://uatapp.com/ [Client.php:1513]
49F3 .|    |    |    => CAS_Client::getURL() [Client.php:1515]
49F3 .|    |    |    <= 'http://uatapp.com/'
49F3 .|    |    |    exit()
49F3 .|    |    |    -
49F3 .|    |    -
49F3 .|    -
4DA8 .START (2019-10-18 14:15:19) phpCAS-1.3.7 ****************** [CAS.php:475]
4DA8 .Loaded configuration:
4DA8 .a:20:{s:12:"cas_hostname";s:14:"myshost";s:14:"cas_real_hosts";s:14:"myshost";s:16:"cas_session_name";s:7:"CASAuth";s:19:"cas_control_session";b:0;s:9:"cas_proxy";b:0;s:8:"cas_port";i:443;s:7:"cas_uri";s:4:"/cas";s:14:"cas_validation";s:0:"";s:8:"cas_cert";s:0:"";s:15:"cas_validate_cn";b:1;s:13:"cas_login_url";s:0:"";s:14:"cas_logout_url";s:65:"http://myshost/cas/logout?service=http://app.com";s:19:"cas_logout_redirect";s:0:"";s:17:"cas_redirect_path";s:30:"http://uatapp.com/";s:15:"cas_enable_saml";b:0;s:11:"cas_version";s:3:"2.0";s:9:"cas_debug";b:1;s:18:"cas_verbose_errors";b:1;s:14:"cas_masquerade";s:0:"";s:20:"cas_session_lifetime";i:120;}
4DA8 .=> phpCAS::client('2.0', 'myshost', 443, '/cas', false) [CasManager.php:93]
4DA8 .|    => CAS_Client::__construct('2.0', false, 'myshost', 443, '/cas', false) [CAS.php:366]
4DA8 .|    |    Starting a new session bsf6k1973lg1o299pp201voo15 [Client.php:933]
4DA8 .|    |    Session is not authenticated [Client.php:939]
4DA8 .|    |    Ticket 'ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org' found [Client.php:1016]
4DA8 .|    <= ''
4DA8 .<= ''
4DA8 .=> phpCAS::setNoCasServerValidation() [CasManager.php:151]
4DA8 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
4DA8 .<= ''
4DA8 .=> phpCAS::setServerLoginURL('') [CasManager.php:52]
4DA8 .<= ''
4DA8 .=> phpCAS::setFixedServiceURL('http://uatapp.com/') [CasManager.php:56]
4DA8 .<= ''
4DA8 .=> phpCAS::setServerLogoutURL('http://myshost/cas/logout?service=http://app.com') [CasManager.php:59]
4DA8 .<= ''
4DA8 .=> phpCAS::checkAuthentication() [CasManager.php:293]
4DA8 .|    => CAS_Client::checkAuthentication() [CAS.php:1100]
4DA8 .|    |    => CAS_Client::isAuthenticated() [Client.php:1326]
4DA8 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1388]
4DA8 .|    |    |    |    no user found [Client.php:1630]
4DA8 .|    |    |    <= false
4DA8 .|    |    |    CAS 2.0 ticket `ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org' is present [Client.php:1441]
4DA8 .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1444]
4DA8 .|    |    |    |     [Client.php:3160]
4DA8 .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3166]
4DA8 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:454]
4DA8 .|    |    |    |    |    <= 'http://uatapp.com/'
4DA8 .|    |    |    |    <= 'http://myshost/cas/serviceValidate?service=http%3A%2F%2Fuatapp.com%2F'
4DA8 .|    |    |    |    => CAS_Client::_readURL('http://myshost/cas/serviceValidate?service=http%3A%2F%2Fuatapp.com%2F&ticket=ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org', NULL, NULL, NULL) [Client.php:3181]
4DA8 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
4DA8 .|    |    |    |    |    |    Response Body:
4DA8 .|    |    |    |    |    |
4DA8 .|    |    |    |    |    |
4DA8 .|    |    |    |    |    |
4DA8 .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    4DA8 .|    |    |    |    |    |    	<cas:authenticationFailure code='INVALID_TICKET'>
        4DA8 .|    |    |    |    |    |    		Target not recognized &#039;ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org&#039;ticket
        4DA8 .|    |    |    |    |    |    	</cas:authenticationFailure>
    4DA8 .|    |    |    |    |    |    </cas:serviceResponse>
4DA8 .|    |    |    |    |    |     [CurlRequest.php:84]
4DA8 .|    |    |    |    |    <= true
4DA8 .|    |    |    |    <= true
4DA8 .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'http://myshost/cas/serviceValidate?service=http%3A%2F%2Fuatapp.com%2F&ticket=ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org', false, false, '<cas:serviceResponse xmlns:cas=\'http://www.yale.edu/tp/cas\'>	<cas:authenticationFailure code=\'INVALID_TICKET\'>		Target not recognized &#039;ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org&#039;ticket	</cas:authenticationFailure></cas:serviceResponse>', 'INVALID_TICKET', 'Target not recognized \'ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org\'ticket') [Client.php:3227]
4DA8 .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:77]
4DA8 .|    |    |    |    |    <= 'http://uatapp.com/'
4DA8 .|    |    |    |    |    CAS URL: http://myshost/cas/serviceValidate?service=http%3A%2F%2Fuatapp.com%2F&ticket=ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org [AuthenticationException.php:80]
4DA8 .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:81]
4DA8 .|    |    |    |    |    Reason: [INVALID_TICKET] CAS error: Target not recognized 'ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org'ticket [AuthenticationException.php:97]
4DA8 .|    |    |    |    |    CAS response:
4DA8 .|    |    |    |    |
4DA8 .|    |    |    |    |
4DA8 .|    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    4DA8 .|    |    |    |    |    	<cas:authenticationFailure code='INVALID_TICKET'>
        4DA8 .|    |    |    |    |    		Target not recognized &#039;ST-521-YAB4ZcVmMHqVm23axq3T-cas01.example.org&#039;ticket
        4DA8 .|    |    |    |    |    	</cas:authenticationFailure>
    4DA8 .|    |    |    |    |    </cas:serviceResponse> [AuthenticationException.php:102]
4DA8 .|    |    |    |    |    exit()
4DA8 .|    |    |    |    |    -
4DA8 .|    |    |    |    -
4DA8 .|    |    |    -
4DA8 .|    |    -`

**Comment by jfritschi** [comment]
Sorry, but debuggin an unknown application that uses its own session management is next to impossible....
Please try it with one of our example. If they work your own custom code is the problem....

I can see that your app is trying to validate the same ticket twice. That's usually a sign of a non functional session system. (e.g. your code that handles sessions, the php session storage is broken)

**Comment by lpx20000** [comment]
thanks, you mean i should use phpcas handler the session with my code ,the problem is that , now my php aplication in use ifram with java application, when them togeter , the problem is show(but together on the chrom browser is ok ), but when i only use my php application on the browser, it's ok ,and the phpcas log is find , so i think if it's problem with the browser?

**Comment by phy25** [comment]
That's weird. You may want to output all cookies, to see if IE strips your cookie somehow, or use Fiddler to see the cookies. I believe this is definitely beyond phpCAS though.

**Comment by lpx20000** [comment]
ok, thinks , other problem , has you met when cas server send logout request to my php application , the cas server lost  connect with my php application , the cas server log show that the socket timeout, it's weird too, and i still trying to find out what the problem,

**Comment by phy25** [comment]
You definitely want more information as well. Can you send a request manually from the CAA server using `curl`?

**Comment by lpx20000** [comment]
sure, i try later, and socket timeout is no always happen,  sometmes logout is ok , i think i should find more log

**Comment by lpx20000** [comment]
the question is still the same ,the problem came out only on ie 11 browser, i had totally had  no idea what to do

**Comment by jfritschi** [comment]
Not much we can do on our end....

Try narrowing down the issues to any of the individual components that are part of the issue:
- Does the IE Error log show anything?
- Can you make a very simple example website to replicate error (e.g. our examples) to simplify the issue
- Compare 2 logins of IE vs Firefox (e.g. phpcas logs, browser logs, cookies in browser, TLS versions used)
- Review web server logs for error/differences

My guess is still that something around your session (cookie) management is broken. This may be due to browser settings or related to browser compatibility.

**Comment by lpx20000** [comment]
@jfritschi thanks for your help, now i can confirm it's the ie setting problem, now i reinstall ie brower, and use low secure level , now the session is fine.

**Comment by lpx20000** [comment]
now it can been closed

**Comment by phy25** [comment]
You can close it yourself but I will go ahead and close this.
