### ISSUE TITLE
Use libcurl+self-signed certificate : unable to get issuer certificate

### ISSUE THREAD

**Issue by wansha** [apereo/phpCAS#321]
# My problem : why use libcurl code connect failed return curl error 60  ,but use curl command can connect  

## 1.  I want to use libcurl to connect to https server , connect failed, and return :
* successfully set certificate verify locations:
*   CAfile: /tmp/ca_sub_2.pem
  CApath: /tmp/
* SSL certificate problem: unable to get issuer certificate
* Closing connection 0

## 2. SSL Certificate Environment:
- The server is use a three-level certificate and is a self-signed certificate.
- I use the CA certificates(/tmp/ca.pem) and second-level certificate( /tmp/ca_sub_2.pem) are also self-signed.

## 3. my test code is (written in c language):

- libcurl version is curl-7.65.3
- openssl version is openssl-1.1.1a
`
 curl = curl_easy_init(); 

if ( curl != NULL ) {  

    printf("Usage:file<%s>;\n",argv[1]);  

    curl_easy_setopt(curl,CURLOPT_URL,argv[1]);  
    curl_easy_setopt(curl,CURLOPT_WRITEFUNCTION,&save_response_callback);  
    curl_easy_setopt(curl,CURLOPT_WRITEDATA,&response);  
    curl_easy_setopt(curl,CURLOPT_SSL_VERIFYPEER,1L); 
    curl_easy_setopt(curl,CURLOPT_SSL_VERIFYHOST,0L);  
    curl_easy_setopt(curl,CURLOPT_VERBOSE,1L);  
    curl_easy_setopt(curl,CURLOPT_POST,1L); 
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, argv[2]);
    curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, strlen(argv[2]));
    curl_easy_setopt(curl,CURLOPT_CAPATH,"/tmp/");  
    curl_easy_setopt(curl,CURLOPT_CAINFO,"/tmp/ca_sub_2.pem");  
    curl_easy_setopt(curl,CURLOPT_CERTINFO,1L);  
    curl_easy_setopt(curl,CURLOPT_TIMEOUT,30);  

    res = curl_easy_perform(curl);  
    if(res != CURLE_OK){  
           printf("curl_wasy_perform error = %s(%d)\n",curl_easy_strerror(res), res);  
    }  

    curl_easy_cleanup(curl);  
}
`

## 4. I use curl command connect ok

- curl command version : curl 7.47.0
- curl command is :curl --cacert /tmp/ca_sub_2.pem -d post_msg post_url -v
- I used in ubuntu.

**Comment by jfritschi** [comment]
I fail to see the link to phpCAS?
