### ISSUE TITLE
DOMDocument::loadXML(): Empty string supplied as input

### ISSUE THREAD

**Issue by SchoebeP** [apereo/phpCAS#347]
Hi i have actually a problem with phpCAS 

F01C .START (2020-06-08 19:58:21) phpCAS-1.3.8 ****************** [CAS.php:475]
F01C .Loaded configuration:
F01C .a:19:{s:12:"cas_hostname";s:17:"cas-uds.grenet.fr";s:14:"cas_real_hosts";s:17:"cas-uds.grenet.fr";s:16:"cas_session_name";s:7:"CASAuth";s:19:"cas_control_session";b:0;s:9:"cas_proxy";b:0;s:8:"cas_port";i:443;s:7:"cas_uri";s:4:"/cas";s:14:"cas_validation";s:0:"";s:8:"cas_cert";s:0:"";s:15:"cas_validate_cn";b:1;s:13:"cas_login_url";s:0:"";s:14:"cas_logout_url";s:33:"https://cas.myuniv.edu/cas/logout";s:19:"cas_logout_redirect";s:0:"";s:17:"cas_redirect_path";s:0:"";s:15:"cas_enable_saml";b:1;s:11:"cas_version";s:16:"SAML_VERSION_1_1";s:9:"cas_debug";b:1;s:18:"cas_verbose_errors";b:1;s:14:"cas_masquerade";s:0:"";}
F01C .=> phpCAS::client('S1', 'cas-uds.grenet.fr', 443, '/cas', false) [CasManager.php:96]
F01C .|    => CAS_Client::__construct('S1', false, 'cas-uds.grenet.fr', 443, '/cas', false) [CAS.php:365]
F01C .|    |    Starting a new session 2gb080hnbl7n0or4ukp6vblak3 [Client.php:932]
F01C .|    |    Session is not authenticated [Client.php:938]
F01C .|    <= ''
F01C .<= ''
F01C .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'cas-uds.grenet.fr',)) [CAS.php:1298]
F01C .|    Not a logout request [Client.php:1744]
F01C .<= ''
F01C .=> phpCAS::setNoCasServerValidation() [CasManager.php:155]
F01C .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
F01C .<= ''
F01C .=> phpCAS::setServerLoginURL('') [CasManager.php:54]
F01C .<= ''
F01C .=> phpCAS::setServerLogoutURL('https://cas.myuniv.edu/cas/logout') [CasManager.php:61]
F01C .<= ''
F01C .=> phpCAS::forceAuthentication() [CasManager.php:169]
F01C .|    => CAS_Client::forceAuthentication() [CAS.php:1120]
F01C .|    |    => CAS_Client::isAuthenticated() [Client.php:1286]
F01C .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1398]
F01C .|    |    |    |    no user found [Client.php:1640]
F01C .|    |    |    <= false
F01C .|    |    |    no ticket found [Client.php:1499]
F01C .|    |    <= false
F01C .|    |    => CAS_Client::redirectToCas(false) [Client.php:1295]
F01C .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1661]
F01C .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
F01C .|    |    |    |    |    Final URI: http://localhost/smartquizzv2/public/login [Client.php:3586]
F01C .|    |    |    |    <= 'http://localhost/smartquizzv2/public/login'
F01C .|    |    |    <= 'https://cas-uds.grenet.fr/cas/login?service=http%3A%2F%2Flocalhost%2Fsmartquizzv2%2Fpublic%2Flogin'
F01C .|    |    |    Redirect to : https://cas-uds.grenet.fr/cas/login?service=http%3A%2F%2Flocalhost%2Fsmartquizzv2%2Fpublic%2Flogin [Client.php:1668]
F01C .|    |    |    exit()
F01C .|    |    |    -
F01C .|    |    -
F01C .|    -
3463 .START (2020-06-08 19:58:27) phpCAS-1.3.8 ****************** [CAS.php:475]
3463 .Loaded configuration:
3463 .a:19:{s:12:"cas_hostname";s:17:"cas-uds.grenet.fr";s:14:"cas_real_hosts";s:17:"cas-uds.grenet.fr";s:16:"cas_session_name";s:7:"CASAuth";s:19:"cas_control_session";b:0;s:9:"cas_proxy";b:0;s:8:"cas_port";i:443;s:7:"cas_uri";s:4:"/cas";s:14:"cas_validation";s:0:"";s:8:"cas_cert";s:0:"";s:15:"cas_validate_cn";b:1;s:13:"cas_login_url";s:0:"";s:14:"cas_logout_url";s:33:"https://cas.myuniv.edu/cas/logout";s:19:"cas_logout_redirect";s:0:"";s:17:"cas_redirect_path";s:0:"";s:15:"cas_enable_saml";b:1;s:11:"cas_version";s:16:"SAML_VERSION_1_1";s:9:"cas_debug";b:1;s:18:"cas_verbose_errors";b:1;s:14:"cas_masquerade";s:0:"";}
3463 .=> phpCAS::client('S1', 'cas-uds.grenet.fr', 443, '/cas', false) [CasManager.php:96]
3463 .|    => CAS_Client::__construct('S1', false, 'cas-uds.grenet.fr', 443, '/cas', false) [CAS.php:365]
3463 .|    |    Starting a new session 2gb080hnbl7n0or4ukp6vblak3 [Client.php:932]
3463 .|    |    Session is not authenticated [Client.php:938]
3463 .|    <= ''
3463 .<= ''
3463 .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'cas-uds.grenet.fr',)) [CAS.php:1298]
3463 .|    Not a logout request [Client.php:1744]
3463 .<= ''
3463 .=> phpCAS::setNoCasServerValidation() [CasManager.php:155]
3463 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
3463 .<= ''
3463 .=> phpCAS::setServerLoginURL('') [CasManager.php:54]
3463 .<= ''
3463 .=> phpCAS::setServerLogoutURL('https://cas.myuniv.edu/cas/logout') [CasManager.php:61]
3463 .<= ''
3463 .=> phpCAS::forceAuthentication() [CasManager.php:169]
3463 .|    => CAS_Client::forceAuthentication() [CAS.php:1120]
3463 .|    |    => CAS_Client::isAuthenticated() [Client.php:1286]
3463 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1398]
3463 .|    |    |    |    no user found [Client.php:1640]
3463 .|    |    |    <= false
3463 .|    |    |    no ticket found [Client.php:1499]
3463 .|    |    <= false
3463 .|    |    => CAS_Client::redirectToCas(false) [Client.php:1295]
3463 .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1661]
3463 .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
3463 .|    |    |    |    |    Final URI: http://localhost/smartquizzv2/public/login [Client.php:3586]
3463 .|    |    |    |    <= 'http://localhost/smartquizzv2/public/login'
3463 .|    |    |    <= 'https://cas-uds.grenet.fr/cas/login?service=http%3A%2F%2Flocalhost%2Fsmartquizzv2%2Fpublic%2Flogin'
3463 .|    |    |    Redirect to : https://cas-uds.grenet.fr/cas/login?service=http%3A%2F%2Flocalhost%2Fsmartquizzv2%2Fpublic%2Flogin [Client.php:1668]
3463 .|    |    |    exit()
3463 .|    |    |    -
3463 .|    |    -
3463 .|    -
3FD5 .START (2020-06-08 19:58:29) phpCAS-1.3.8 ****************** [CAS.php:475]
3FD5 .Loaded configuration:
3FD5 .a:19:{s:12:"cas_hostname";s:17:"cas-uds.grenet.fr";s:14:"cas_real_hosts";s:17:"cas-uds.grenet.fr";s:16:"cas_session_name";s:7:"CASAuth";s:19:"cas_control_session";b:0;s:9:"cas_proxy";b:0;s:8:"cas_port";i:443;s:7:"cas_uri";s:4:"/cas";s:14:"cas_validation";s:0:"";s:8:"cas_cert";s:0:"";s:15:"cas_validate_cn";b:1;s:13:"cas_login_url";s:0:"";s:14:"cas_logout_url";s:33:"https://cas.myuniv.edu/cas/logout";s:19:"cas_logout_redirect";s:0:"";s:17:"cas_redirect_path";s:0:"";s:15:"cas_enable_saml";b:1;s:11:"cas_version";s:16:"SAML_VERSION_1_1";s:9:"cas_debug";b:1;s:18:"cas_verbose_errors";b:1;s:14:"cas_masquerade";s:0:"";}
3FD5 .=> phpCAS::client('S1', 'cas-uds.grenet.fr', 443, '/cas', false) [CasManager.php:96]
3FD5 .|    => CAS_Client::__construct('S1', false, 'cas-uds.grenet.fr', 443, '/cas', false) [CAS.php:365]
3FD5 .|    |    Starting a new session 2gb080hnbl7n0or4ukp6vblak3 [Client.php:932]
3FD5 .|    |    Session is not authenticated [Client.php:938]
3FD5 .|    |    Ticket 'ST-2226293-kxfRBP6UPYdNYnqv7cXv-cas-uds.grenet.fr' found [Client.php:1026]
3FD5 .|    <= ''
3FD5 .<= ''
3FD5 .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'cas-uds.grenet.fr',)) [CAS.php:1298]
3FD5 .|    Not a logout request [Client.php:1744]
3FD5 .<= ''
3FD5 .=> phpCAS::setNoCasServerValidation() [CasManager.php:155]
3FD5 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1664]
3FD5 .<= ''
3FD5 .=> phpCAS::setServerLoginURL('') [CasManager.php:54]
3FD5 .<= ''
3FD5 .=> phpCAS::setServerLogoutURL('https://cas.myuniv.edu/cas/logout') [CasManager.php:61]
3FD5 .<= ''
3FD5 .=> phpCAS::forceAuthentication() [CasManager.php:169]
3FD5 .|    => CAS_Client::forceAuthentication() [CAS.php:1120]
3FD5 .|    |    => CAS_Client::isAuthenticated() [Client.php:1286]
3FD5 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1398]
3FD5 .|    |    |    |    no user found [Client.php:1640]
3FD5 .|    |    |    <= false
3FD5 .|    |    |    SAML 1.1 ticket `ST-2226293-kxfRBP6UPYdNYnqv7cXv-cas-uds.grenet.fr' is present [Client.php:1480]
3FD5 .|    |    |    => CAS_Client::validateSA('', NULL, NULL, false) [Client.php:1483]
3FD5 .|    |    |    |    => CAS_Client::getServerSamlValidateURL() [Client.php:2072]
3FD5 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:477]
3FD5 .|    |    |    |    |    |    Final URI: http://localhost/smartquizzv2/public/login [Client.php:3586]
3FD5 .|    |    |    |    |    <= 'http://localhost/smartquizzv2/public/login'
3FD5 .|    |    |    |    <= 'https://cas-uds.grenet.fr/cas/samlValidate?TARGET=http%3A%2F%2Flocalhost%2Fsmartquizzv2%2Fpublic%2Flogin'
3FD5 .|    |    |    |    => CAS_Client::_readURL('https://cas-uds.grenet.fr/cas/samlValidate?TARGET=http%3A%2F%2Flocalhost%2Fsmartquizzv2%2Fpublic%2Flogin', NULL, NULL, NULL) [Client.php:2080]
3FD5 .|    |    |    |    |    => CAS_Client::_buildSAMLPayload() [Client.php:2868]
3FD5 .|    |    |    |    |    <= '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol"  MajorVersion="1" MinorVersion="1" RequestID="_192.168.16.51.1024506224022" IssueInstant="2002-06-19T17:03:44.022Z"><samlp:AssertionArtifact>ST-2226293-kxfRBP6UPYdNYnqv7cXv-cas-uds.grenet.fr</samlp:AssertionArtifact></samlp:Request></SOAP-ENV:Body></SOAP-ENV:Envelope>'
3FD5 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
3FD5 .|    |    |    |    |    |    Response Body: 
3FD5 .|    |    |    |    |    |    
3FD5 .|    |    |    |    |    |     [CurlRequest.php:84]
3FD5 .|    |    |    |    |    <= true
3FD5 .|    |    |    |    <= true
3FD5 .|    |    |    |    server version: S1 [Client.php:2089]

![image](https://user-images.githubusercontent.com/45164206/84074985-bcdcc500-a9d3-11ea-8a46-f51e1b71b6e2.png)
 PLZZZZ help me

**Comment by jfritschi** [comment]
The CAS server is sending an empty response or no response is given at all:

```
3FD5 .| | | | | | Response Body:
3FD5 .| | | | | |
3FD5 .| | | | | | [CurlRequest.php:84]
```

Please review the CAS server log for errors and also make sure any https requests by phpCAS can reach the CAS server (firewall, routing, dns resolution etc.). Best use a commandline tool (e.g. curl) to query the CAS server.

It seems your client is using "localhost" as a service URL to be verified. This could be a source of error. You can also try different CAS protocols instead of SAML validation.

**Comment by Dieudonnne** [comment]
If i use this 👍 

$settings = array(
            'cas_hostname' => 'cas-uds.grenet.fr',
            'cas_port' => 443,
            'cas_path' => '',
            'logoutUrl' => 'http://localhost/smartquizzv2/public/',
        );

        phpCAS::client( SAML_VERSION_1_1, $settings[ "cas_hostname" ], $settings[
        "cas_port"], "", false );
        phpCAS::setNoCasServerValidation();
        phpCAS::setNoClearTicketsFromUrl();
        phpCAS::setFixedServiceURL( $settings[ "logoutUrl" ] );
        phpCAS::setLang( PHPCAS_LANG_FRENCH );
        phpCAS::setExtraCurlOption( CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );
        phpCAS::forceAuthentication(); 

everything works

**Comment by jfritschi** [comment]
Closing since no further details are being provided. Please reopen if you can provide more info.
