### ISSUE TITLE
When the new version is coming?

### ISSUE THREAD

**Issue by Magiczne** [apereo/phpCAS#363]
Hi!

When is the next release planned? There is one feature on the master branch  that we want to use, but we don't want to include `dev-*` in our composer.

The feature that I'm talking about is the getter for `private static $_PHPCAS_CLIENT;` variable.

Thanks in advance for answer.

**Comment by jfritschi** [comment]
I can work on cutting a new release within the next few weeks. Any objections from @phy25 ?

**Comment by Magiczne** [comment]
@jfritschi that would be great

**Comment by phy25** [comment]
@jfritschi Sounds good (sorry life has been busy). It has been a year since the last release...

**Comment by jfritschi** [comment]
I have just cut a new release. Hope everything is okay ... I was in a rush ;-)
