### ISSUE TITLE
PHPCas on PHP 8 and PHP7.4 refused to work

### ISSUE THREAD

**Issue by Acksop** [apereo/phpCAS#364]
I get a message of Deprecated function:

__autoload() is no longer supported, use spl_autoload_register() instead in  /vendor/apereo/phpcas/source/CAS/Autoload on line 99

Can you improve PHP 8.0 Support ?

**Comment by jfritschi** [comment]
Which version of phpCAS are you using?

**Comment by phy25** [comment]
Looks like line 99 is here (3 years ago): https://github.com/apereo/phpCAS/commit/381dfdb4dd99b0cfe126e48ac85646521c61f1ab#diff-1695d12e397d8faa6c0dff03e7f598ab9af81df4e1442ca406982913a38a1a53L99

Please update to the latest phpCAS version. If you have other questions feel free to reply.

**Comment by Acksop** [comment]
nop phy25, php8.0 review this error, in fact `__autoload` method is déprecated !

**Comment by phy25** [comment]
Ok. Could you confirm if you are using the latest phpCAS version?

**Comment by Acksop** [comment]
I use on composer: 
` "apereo/phpcas": "^1.3",`

But it seems that at startup, only at startup of the application that there is an error about the __autoload on php8.0,
and after it work.

The error is like above : 

`__autoload() is no longer supported, use spl_autoload_register() instead in /vendor/apereo/phpcas/source/CAS/Autoload on line 99`

**Comment by phy25** [comment]
Weird, that line has been removed since 1.3.6: https://github.com/apereo/phpCAS/commit/381dfdb4dd99b0cfe126e48ac85646521c61f1ab

You might want to do a [`composer update`](https://getcomposer.org/doc/03-cli.md#update-u) or check if some other dependency locks you on an old phpCAS version.
