### ISSUE TITLE
session_set_save_handler(): Cannot change save handler when session is active

### ISSUE THREAD

**Issue by fglueck** [apereo/phpCAS#365]
```
public function __construct(
...
        \SessionHandlerInterface $sessionHandler = null
    ) {
...
        if (empty($sessionHandler)) {
            $sessionHandler = new CAS_Session_PhpSession;
        }
...
        $this->setSessionHandler($sessionHandler);
```
this calls session_set_save_handler and that won't work if the session is allready startet.
Simple workaround would be:
```
public function __construct(
...
        \SessionHandlerInterface $sessionHandler = null
    ) {
...
        if (!empty($sessionHandler)) {
            $this->setSessionHandler($sessionHandler);
        }
...

```
Greetings
Frank

**Comment by glazilla** [comment]
Same issue...

**Comment by lucasbrtd** [comment]
Same issue

While waiting for the fix, you can comment on these two pieces of code :

Client.php:928-930
```
//        if (empty($sessionHandler)) {
//            $sessionHandler = new CAS_Session_PhpSession;
//        }
...
```
Client.php:937
```
//        $this->setSessionHandler($sessionHandler);
```

And it's working

**Comment by jfritschi** [comment]
Can you please confirm the version you are using and provide parts of the debug log?

**Comment by lucasbrtd** [comment]
I'm using the l3/cas-bundle which use the jasig/phpcas in version 1.3.9
I got this message in my homepage and in my debug log I have "200 OK"
![image](https://user-images.githubusercontent.com/32938032/106740611-ee696700-661a-11eb-8709-97b738cda5aa.png)

**Comment by Robszyy** [comment]
@lucasbrtd thanks for the tip.

I'm also using **l3/cas-bundle** and I also got the same error.
To fix this, I added ` \phpCAS::setVerbose(true);` to Security/CasListener.php (L:30)
Between `\phpCAS::setDebug(false)` and `\phpCAS::client(...)`

**Comment by jfritschi** [comment]
My guess would be that the correct fix is to verify with session_status ( ) if there is an already existing session before setting the session_set_save_handler?

Not sure though... Will need to investigate. I assume this was broken in #340

@phy25 Any thoughts?

**Comment by robellet** [comment]
Same issue:

phpCAS error: phpCAS::client(): ErrorException: Warning: session_set_save_handler(): Cannot change save handler when session is active

**Comment by fglueck** [comment]
Using current version 1.3.9 (fetched with composer from git)

Here is one example:
`
Meldung: (0) session_set_save_handler(): Cannot change save handler when session is active
Skriptname: /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS/Client.php
Zeile: 1116;
SCRIPT_NAME: /index.php
PHP_SELF: /index.php
USER: 

Trace:
#0 /srv/www/html/cockpit/inc/exceptionhandler.class.php(120): ExceptionHandler::alert('unbehandelter F...', Object(ErrorException))
#1 [internal function]: ExceptionHandler->errorHandler(2, 'session_set_sav...', '/srv/www/html/c...', 1116, Array)
#2 /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS/Client.php(1116): session_set_save_handler(Object(CAS_Session_PhpSession), true)
#3 /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS/Client.php(937): CAS_Client->setSessionHandler(Object(CAS_Session_PhpSession))
#4 /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS.php(366): CAS_Client->__construct('2.0', false, 'mappsacc.mazdae...', 443, '/cas', true, Object(CAS_Session_PhpSession))
#5 /srv/www/html/cockpit/inc/vendor/mazda/ssoapiclient/src/SSOAuthClient.php(137): phpCAS::client('2.0', 'mappsacc.mazdae...', 443, '/cas')
#6 /srv/www/html/cockpit/inc/vendor/mazda/ssoapiclient/src/SSOAuthClient.php(223): Mazda\SSOAuthClient->initCasClient()
#7 /srv/www/html/cockpit/inc/auth.class.php(946): Mazda\SSOAuthClient->authenticate()
#8 /srv/www/html/cockpit/inc/auth.class.php(65): auth->loginCAS()
#9 /srv/www/html/cockpit/inc/auth.class.php(37): auth->authUser(NULL)
#10 /srv/www/html/cockpit/inc/settings.php(49): auth->checkAuth()
#11 /srv/www/html/cockpit/public/index.php(11): require_once('/srv/www/html/c...')
#12 {main}
`

and here is a second:
`
Meldung: (0) session_set_save_handler(): Cannot change save handler when session is active
Skriptname: /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS/Client.php
Zeile: 1116;
SCRIPT_NAME: /index.php
PHP_SELF: /index.php
USER: 

Trace:
#0 /srv/www/html/cockpit/inc/exceptionhandler.class.php(120): ExceptionHandler::alert('unbehandelter F...', Object(ErrorException))
#1 [internal function]: ExceptionHandler->errorHandler(2, 'session_set_sav...', '/srv/www/html/c...', 1116, Array)
#2 /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS/Client.php(1116): session_set_save_handler(Object(CAS_Session_PhpSession), true)
#3 /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS/Client.php(937): CAS_Client->setSessionHandler(Object(CAS_Session_PhpSession))
#4 /srv/www/html/cockpit/inc/vendor/apereo/phpcas/source/CAS.php(366): CAS_Client->__construct('2.0', false, 'mappsacc.mazdae...', 443, '/cas', true, Object(CAS_Session_PhpSession))
#5 /srv/www/html/cockpit/inc/vendor/mazda/ssoapiclient/src/SSOAuthClient.php(137): phpCAS::client('2.0', 'mappsacc.mazdae...', 443, '/cas')
#6 /srv/www/html/cockpit/inc/vendor/mazda/ssoapiclient/src/SSOAuthClient.php(311): Mazda\SSOAuthClient->initCasClient()
#7 /srv/www/html/cockpit/inc/auth.class.php(967): Mazda\SSOAuthClient->logout(Array)
#8 /srv/www/html/cockpit/inc/settings.php(46): auth->logoutCAS()
#9 /srv/www/html/cockpit/public/index.php(11): require_once('/srv/www/html/c...')
#10 {main}
`

**Comment by wdiaz** [comment]
I had to revert to 1.3.8 because the latest update broke my platform.
I'm running Ubuntu 18.08 & PHP 7.2.

**Comment by wdiaz** [comment]
> @lucasbrtd thanks for the tip.
> 
> I'm also using **l3/cas-bundle** and I also got the same error.
> To fix this, I added ` \phpCAS::setVerbose(true);` to Security/CasListener.php (L:30)
> Between `\phpCAS::setDebug(false)` and `\phpCAS::client(...)`

**Comment by jfritschi** [comment]
I have added a fix. Can you please verify if it works for your use cases?

**Comment by wdiaz** [comment]
> I have added a fix. Can you please verify if it works for your use cases?

Copied. I'll give you an update asap.

**Comment by lucasbrtd** [comment]
> I have added a fix. Can you please verify if it works for your use cases?

Yeah it works for me. I replaced what you changed in your fix, in my project and I am redirected to the home page of my CAS ^^

**Comment by jfritschi** [comment]
> > I have added a fix. Can you please verify if it works for your use cases?
> 
> Will the change be on 1.3.10?.

Yes, definitely. I have already tagged this issue as part of the 1.3.10 release... I will probably release 1.3.10 before the end of February. There are some other things that need to be fixed before cutting a new release.

**Comment by jfritschi** [comment]
> > I have added a fix. Can you please verify if it works for your use cases?
> 
> Yeah it works for me. I replaced what you changed in your fix, in my project and I am redirected to the home page of my CAS ^^

Thanks @lucasbrtd

**Comment by jlherren** [comment]
I'm also affected by this. I wonder if perhaps the session should not be touched in any way whatsoever if `changeSessionID = false` was passed into `phpCAS::client(...)`.

**Comment by fglueck** [comment]
bugfix works for me, too

**Comment by viduc** [comment]
same issue with 1.3.9
![Clipboard - 12 février 2021 09-43](https://user-images.githubusercontent.com/5895566/108088405-b5001500-7078-11eb-926c-61bf94b7aeeb.png)

**Comment by wdiaz** [comment]
> same issue with 1.3.9
> ![Clipboard - 12 février 2021 09-43](https://user-images.githubusercontent.com/5895566/108088405-b5001500-7078-11eb-926c-61bf94b7aeeb.png)

Try using version 1.3.8. I moved back to 1.3.8  because the fix will be released on the 1.3.10 version and I can't wait (neither can use master). At least on my stack 7.2 and 18.04 it does work.

**Comment by viduc** [comment]
ok thanks , work fine with 1.3.8, will wait future version no problem...

**Comment by Mick3DIY** [comment]
> I have added a fix. Can you please verify if it works for your use cases?

It works ! Thanks a lot ! :)

> Symfony 4.4, php 7.3, jasig/phpcas 1.3.9 without any bundle

**Comment by jfritschi** [comment]
Release 1.4.0 has been released.
