### ISSUE TITLE
$server_port documented to be a string, but that causes an exception

### ISSUE THREAD

**Issue by jlherren** [apereo/phpCAS#369]
I just updated from version 1.3.8 to 1.3.9. The PhpDoc of `phpCAS::client()` was changed in this version and the `$server_port` argument is now documented to be `string` instead of `int` (PR #340). However passing a string will not work and cause a failure, since the type of that argument will be checked in `CAS_Client`'s constructor.

This doesn't really break anything, it's just a wrong PhpDoc. But it causes static analyzers (I use PHPStan) to flag it.  The PhpDoc-type should probably be reverted to be `int` (or proper support for named ports should be added).

**Comment by jfritschi** [comment]
Thanks, good catch. Indeed an error in the code documentation.

**Comment by jfritschi** [comment]
Fixed. Thank you!
