### ISSUE TITLE
Latest release is set to 1.3.8

### ISSUE THREAD

**Issue by TechnologyClassroom** [apereo/phpCAS#372]
I noticed that there is a 1.3.9, but the [latest release](https://github.com/apereo/phpCAS/releases/latest) points to 1.3.8.  Is this an issue with tagging or is 1.3.9 unstable?

**Comment by jfritschi** [comment]
Version 1.3.9 has some major issues #365  that affect some users but most importantly the travis integration (incl. release upload) is broken and needs fixing #366
I only have limited time at the moment to start debugging the issues... Hopefully I can get everything solved in the next 1-2 weeks.

**Comment by jfritschi** [comment]
Release 1.4.0 has been released
