### ISSUE TITLE
PHP 8 redirect issue

### ISSUE THREAD

**Issue by WindowsNT** [apereo/phpCAS#376]
In PHP 7.4, the following works well:

```
$cas_host = 'sso.sch.gr';
$cas_context = '';
$cas_port = 443;
$cas_server_ca_cert_path = 'cachain.pem';
phpCAS::client(SAML_VERSION_1_1, $cas_host, $cas_port, $cas_context);
phpCAS::setNoCasServerValidation();
phpCAS::forceAuthentication();
```

While trying it at PHP 8.0, I have a too many redirects issue. Enabling debugging and/or verbose messages do not seem to work.

Great library btw.

**Comment by phy25** [comment]
> Enabling debugging and/or verbose messages do not seem to work.

The purpose of those are for troubleshooting rather than magically making things work. Could you attach the debug logs?

Also could you provide more information about your environment? is your PHP config the same between 7.4 and 8?

**Comment by WindowsNT** [comment]
I meant that there were no messages in output (but perhaps it writes to a log file).
I fixed it temporarily by adding

   ` phpCAS::setNoClearTicketsFromUrl();`

will research more on it later.

**Comment by phy25** [comment]
I am on a phone and I can't find the doc about debugging right now, but this might help: #295

**Comment by jfritschi** [comment]
Can we close the issues or is this still active?
