### ISSUE TITLE
deprecation warning in php 8.1.2

### ISSUE THREAD

**Issue by carl-welch** [apereo/phpCAS#416]
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /path/to/vendor/apereo/phpcas/source/CAS/Client.php on line 1041

Maybe change null to the empty string on line 1040?

$ticket = (isset($_GET['ticket']) ? $_GET['ticket'] : '');

**Comment by jfritschi** [comment]
This issue may have been solved with a recent pull

https://github.com/apereo/phpCAS/pull/415

Can you please check against the current master branch?

**Comment by carl-welch** [comment]
Yes, I was looking at the v1.4.0 release and didn't think to look at master. Sorry about that. Looks great, tnx.
