### ISSUE TITLE
Is there a way to use phpCAS within a Symfony API REST?

### ISSUE THREAD

**Issue by lazaro92** [apereo/phpCAS#420]
Hi, I'm developing and application that needs to connect to a CAS service in order to see if the user logged via another application. The problem I have is that this library seems that is not designed for API REST and, when the front makes an AJAX call, the server sends a redirect to the service, but redirects don't work in AJAX calls.

 So is there a wall that the API can send the route to go in a JSON instead of doing a redirect?

So `phpCAS::checkAuthentication())`, instead of make a redirection, it could return an object with the Location URL in order to make the redirection from the front application.

**Comment by phy25** [comment]
CAS works based off authentication server reading its cookies from the browser and passing token back to the resource server, and generally there is no way for you to REST call authentication server without a ticket. I am afraid you need to work around it browser side by iframing the CAS login page to get the ticket for example. If you would like to learn more about CAS protocol, I recommend https://apereo.github.io/cas/6.5.x/protocol/CAS-Protocol.html
