### ISSUE TITLE
Autoload.php should not emit a composer-preferred warning

### ISSUE THREAD

**Issue by osidd** [apereo/phpCAS#424]
phpCAS emits a warning on every load: `phpCAS autoloader is deprecated. Install phpCAS using composer instead`

The error output was added in dde1fa1f9c836be7cc1d13017d1a4425365a654d by @jdufresne and should be reverted.

The error pointlessly clutters logs and debugging output for websites & frameworks that can't do anything about the setup (eg, Drupal7).

Arguably this library shouldn't "care" how it was installed (diminishes the object abstraction we should be working towards), but regardless such a warning belongs in a coding standards or other document, not in PHP error_logging.

**Comment by phy25** [comment]
My take here would be if we do plan to remove this eventually, this log is worthwhile, but I kind of forgot the context and will need to look into this more. Sorry if this sounds like a fast but unhelpful response.

**Comment by adoy** [comment]
From my point of view triggering an `E_DEPRECATED_USER` is correct. This is the exact reason this error level exists. The problem here is that compser is not loading the `source/CAS.php` file. I created #422 to fix this.

**Comment by jfritschi** [comment]
I have merge the PR. Thanks!
