### ISSUE TITLE
login with 1.6.0 wrong redirection

### ISSUE THREAD

**Issue by imaginabit** [apereo/phpCAS#427]
In the laravel project im working we update with composer from "apereo/phpcas": "1.5.0" to 1.6.0 

them when try to access to cas login the url it redirects stay on http//example.com/mylaraveldir/cas/login and show a blank page

but when I turn it back to 1.5.0 it show me the right url somehing like: 
https://example.com/cas/login?service=http//example.com/mylaraveldir/cas/login 

and the usual cas login form, is there any change that I have to do in the configuration with the new version or is something wrong ?

**Comment by phy25** [comment]
If you turn on PHP error log you should be able to see more information. However, there is a breaking change meant to address a security issue in 1.6.0: https://github.com/apereo/phpCAS/blob/master/docs/Upgrading

**Comment by phy25** [comment]
Please feel free to reopen if you have further information.
