### ISSUE TITLE
Any plans on upgrading to PHP 8.0 or above ?

### ISSUE THREAD

**Issue by belanasaikiran** [apereo/phpCAS#440]
Hi, I just migrated my existing PHP application from 7.4 to 8.0 and the CAS doesn't seem to be working. 
Any plans on upgrading the `phpCAS` to 8.0 ?

**Comment by phy25** [comment]
When you say it doesn’t work what is the error message? What CAS version are you using?

**Comment by belanasaikiran** [comment]
I'm using `1.6.1` and my application uses php8.0.
