### ISSUE TITLE
CAS_AuthenticationException cannot be caught

### ISSUE THREAD

**Issue by dzoltok** [apereo/phpCAS#64]
We are using phpCAS to provide single-sign-on functionality through a set of Symfony 2.1 applications. During our testing, we have noticed that requesting a secured page with an invalid ticket parameter throws a CAS_AuthenticationException instead of returning false. This leads to the page returning a 500 error and the printf statement in the exception constructor printing straight to the browser.

It seems like, if a given ticket is invalid, that isn't an error and checking authentication should simply return false instead of throwing an uncatchable exception and breaking page rendering.

Relevant portion of the stacktrace:

```
 in /Users/dzoltok/Sites/cls/www/vendor/sln/user-bundle/SLN/Bundle/UserBundle/lib/cas/CAS/Client.php at line 2839  -+

            } else if ( $tree_response->getElementsByTagName("authenticationFailure")->length != 0) {
                // authentication succeded, extract the error code and message
                $auth_fail_list = $tree_response->getElementsByTagName("authenticationFailure");
                throw new CAS_AuthenticationException(
                    $this, 'Ticket not validated', $validate_url,
                    false/*$no_response*/, false/*$bad_response*/,
                    $text_response,

at CAS_Client ->validateCAS20 ('https://sln.localhost/app_dev.php/serviceValidate?service=http%3A%2F%2Fcls.localhost%2Fapp_dev.php%2Fprize%2F&ticket=ST-askldjfhalsdhf', '<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'> <cas:authenticationFailure code="INVALID_TICKET" /> </cas:serviceResponse>', object(DOMElement))
in /Users/dzoltok/Sites/cls/www/vendor/sln/user-bundle/SLN/Bundle/UserBundle/lib/cas/CAS/Client.php at line 1224  -+
at CAS_Client ->isAuthenticated ()
in /Users/dzoltok/Sites/cls/www/vendor/sln/user-bundle/SLN/Bundle/UserBundle/lib/cas/CAS.php at line 1151  -+
at phpCAS ::isAuthenticated ()
in /Users/dzoltok/Sites/cls/www/vendor/sln/user-bundle/SLN/Bundle/UserBundle/Entity/CASServer.php at line 146  -+
```

**Comment by alexboss** [comment]
Had the same problem of uncaught exceptions in my organization.
Has been solved adding an additional exception handler using ```set_exception_handler```
See http://php.net/manual/en/function.set-exception-handler.php
Alexandre 8)
