### ISSUE TITLE
Bad response from the CAS server AuthenticationException

### ISSUE THREAD

**Issue by Jing-Springshare** [apereo/phpCAS#92]
I am trying to use phpCAS 1.3.2 to integrated with secure.its.yale.edu. It looks like I am authenticated at yale side, however, in phpCAS side, I got

> Warning: DOMDocument::loadXML(): Empty string supplied as input in /opt/php/auth/protected/cas/CAS-1.3.2/CAS/Client.php on line 2778
> 
> Fatal error: Uncaught exception 'CAS_AuthenticationException' in /opt/php/auth/protected/cas/CAS-1.3.2/CAS/Client.php:2780
> Stack trace:
> # 0 /opt/php/auth/protected/cas/CAS-1.3.2/CAS/Client.php(1224): CAS_Client->validateCAS20('https://secure....', '', NULL)
> # 1 /opt/php/auth/protected/cas/CAS-1.3.2/CAS/Client.php(1083): CAS_Client->isAuthenticated()
> # 2 /opt/php/auth/protected/cas/CAS-1.3.2/CAS.php(1101): CAS_Client->forceAuthentication()
> # 3 /opt/php/auth/www/cas/auth.php(44): phpCAS::forceAuthentication()
> # 4 {main}
> 
>   thrown in /opt/php/auth/protected/cas/CAS-1.3.2/CAS/Client.php on line 2780

In the debug log

> 2545 .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://secure.its.yale.edu/cas/login/serviceValidate?service=http%3A%2F%2Fwww.nlit.com%2Fphp%2Fauth%2Fwww%2Fcas%2Fauth.php&ticket=ST-354552-MjM37RgIsbf904oALyDf-cas', false, true, '') [Client.php:2783]
> 2545 .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
> 2545 .|    |    |    |    |    <= 'http://www.nlit.com/php/auth/www/cas/auth.php'
> 2545 .|    |    |    |    |    CAS URL: https://secure.its.yale.edu/cas/login/serviceValidate?service=http%3A%2F%2Fwww.nlit.com%2Fphp%2Fauth%2Fwww%2Fcas%2Fauth.php&ticket=ST-354552-MjM37RgIsbf904oALyDf-cas [AuthenticationException.php:79]
> 2545 .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
> 2545 .|    |    |    |    |    Reason: bad response from the CAS server [AuthenticationException.php:85]
> 2545 .|    |    |    |    |    CAS response:  [AuthenticationException.php:100]
> 2545 .|    |    |    |    |    exit()

On the other hand, I setup my own cas server 3.5.2 and everything works fine. I don't know what version that yale.edu runs. Is it a backward compatibility issue?

**Comment by magnumsferrari** [comment]
If you are using Drupal and get this error, you might have the same issue I had. I switched the CAS server version setting from 3.0 to 2.0 and its working now. Guess my CAS server is really old...

Running drupal version 7.56, phpCAS 1.3.5, php 5.6.32, Libraries module version 7.x-2.3, drupal cas module version 7.x-1.6. No idea what exact CAS server version the cas server is running.
